<?php 
date_default_timezone_set('EST');
$page_heading = 'The cURL Tutorial by DistroTube';
$title = 'SThe cURL Tutorial by DistroTube';
$lastMod = "Modified: " . date("D M j Y G:i:s T", getlastmod());
?>
<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8"> 
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>
    <?php print $title; ?>
  </title>
  <link rel="icon" type="image/ico" href="favicon.ico">
  <link rel="shortcut icon" type="image/ico" href="favicon.ico">
  <style>
/** if needed add style here */
  </style>
    <link 
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" 
        rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" 
        crossorigin="anonymous">    <!-- BOOTSTRAP STYLE -->
    <link 
        rel="stylesheet" 
        href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link 
        href="https://api.mapbox.com/mapbox-gl-js/v2.1.1/mapbox-gl.css" 
        rel="stylesheet">
    <link 
        href="css/notes.css" 
        rel="stylesheet" 
        type="text/css">
</head>

<body>

  <div id="pagewidth" class="container">
 
    <section id="header">  <!-- #HEADER -->
        <h1 class="bg-dark text-light text-end pe-3"><?php print $page_heading; ?></h1>
    </section>
    <section class="content">
      <div class="notes">                           
        <div class="content">
            <h2>The cURL Tutorial by DistroTube</h2>
            <dl>
                <dt>Basic functions</dt>
                <dd>
                    <ul>
                        <li>curl wttr.in - returns a weather report</li>
                        <li>curl ifconfig.co - returns (my) IP addr</li>
                        <li>GET  THE WEATHER: curl wttr.in (or curl wttr.in/Berlin for city)</li>
                        <li>GET YOUR IP ADDRESS - curl ifconfig.co</li>
<li>GET YOUR LOCATION - curl ifconfig.co/country ( curl ifconfig.co/city )</li>
<li>TINYURL URL SHORTENER - curl -s http://tinyurl.com/api-create.php?url...</li>

<li>GETNEWS.TECH - curl getnews.tech curl getnews.tech/trump curl getnews.tech/nba+finals</li>

<li>CHEAT SHEETS - curl cheat.sh/btrfs</li>

<li>CRYPTOCURRENCY EXCHANGE RATES - curl rate.sx</li>

<li>DICTIONARY - curl 'dict://dict.org/d:operating system'</li>

<li>FUN WITH PARROTS - curl parrot.live
(also checkout parrotsay: https://github.com/matheuss/parrotsay )</li>

<li>FUN WITH RICK ASTLEY - https://github.com/keroserene/rickrollrc</li>
                    </ul>
                </dd>
            </dl>

        </div><!--    $    END class.content (former id.maincol)    $    -->
      </div>                                        <!--    .notes      -->
    </section>
    <section class="footer px-4">                   <!--    .FOOTER     -->
        <div class="row gx-5">
            <div class="col"><div class="p-3 border bg-light"> Based on Notes by <a href="https://github.com/ajaxStardust" target="_blank" title="View original">@ajaxStardust</a> <em>Laravel</em> notes:</div></div>
            <div class="col"><div class="p-3 border bg-light text-end"><kbd><?php echo $lastMod; ?></kbd></div></div>
        </div>
    </section>      
  </div>                                            <!--    .content  -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
</body>
</html>