<?php

// namespace Trn\Inc\Admin;

include $_SERVER['DOCUMENT_ROOT'].'/zjvuypqa/public_html/wp-config.php';

$page_heading = 'Experiment for checking the depth of the plugin';
$title = 'Depth Test';

function get_my_plugin_root_dir()
{
    $path_to_this_files_dir_without_wp_plugin_dir = str_replace(WP_PLUGIN_DIR, '', __DIR__);

    $file_depth = preg_replace('@([\x5c\x2f])@', '/', __FILE__);
    $solidus_count = substr_count($file_depth, '/');
    $target_folder = $solidus_count - 5; // ENTER HERE THE NUMBER OF SUBDIRECTORIES FROM DOCUMENT_ROOT
    $plugin_directory_name_only = explode(DIRECTORY_SEPARATOR, $path_to_this_files_dir_without_wp_plugin_dir)[$target_folder];

    return WP_PLUGIN_DIR.DIRECTORY_SEPARATOR.$plugin_directory_name_only;
}

$file_depth = preg_replace('@([\x5c\x2f])@', '/', __FILE__);
$solidus_count = substr_count($file_depth, '/');
$target_folder = $solidus_count - 5;

$path_to_this_files_dir_without_wp_plugin_dir = str_replace(WP_PLUGIN_DIR, '', __DIR__);
$plugin_directory_name_only = explode(DIRECTORY_SEPARATOR, $path_to_this_files_dir_without_wp_plugin_dir)[$target_folder];
?>
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        <?php echo $title; ?>
    </title>
    <link rel="icon" type="image/ico" href="favicon.ico">
    <link rel="shortcut icon" type="image/ico" href="favicon.ico">
    <style>
    .red {
        color: #F00;
    }
    .keyTerms {
        background: linear-gradient(0deg, rgba(255,255,255,1) 0%, rgba(235,235,255,1) 80%, rgba(214,214,235,1) 93%, rgba(173,173,214,1) 100%); 
        margin-top: 1rem;
        padding-top:0.5rem;
}
       }
    </style>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <!-- BOOTSTRAP STYLE -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.1.1/mapbox-gl.css" rel="stylesheet">
    <link href="css/notes.css" rel="stylesheet" type="text/css">
</head>

<body>

    <div id="pagewidth" class="container">

        <section id="header">
            <!-- #HEADER -->
            <h1 class="bg-dark text-light text-end pe-3"><?php echo $page_heading; ?></h1>
        </section>
        <section>
            <?php
      echo '<p>Solidus count from DOCUMENT_ROOT to this file: '.$solidus_count.'</p><dl>';
echo '<dt class="keyTerms">plugin_dir_url(dirname(__FILE__))</dt><dd>'.plugin_dir_url(dirname(__FILE__)).'</dd>';
echo '<dt class="keyTerms">plugin_dir_path(dirname(__FILE__, 2))</dt><dd>'.plugin_dir_path(dirname(__FILE__, 2)).'</dd>';
echo '<dt class="keyTerms">plugins_url()</dt><dd>'.plugins_url().'</dd>';
echo '<dt class="keyTerms">__FILE__</dt><dd>'.__FILE__.'</dd>';
echo '<dt class="keyTerms">variable: <strong>$plugin_directory_name_only</strong></dt><dd>'.$plugin_directory_name_only.'</dd>';
echo '<dt class="keyTerms">WP_PLUGIN_DIR</dt><dd>'.WP_PLUGIN_DIR.'</dd>';
echo '<dt class="keyTerms">str_replace(WP_PLUGIN_DIR, "", __DIR__))</dt><dd>'.str_replace(WP_PLUGIN_DIR, '', __DIR__).'</dd>';
echo '<dt class="keyTerms">explode(DIRECTORY_SEPARATOR, $path_to_this_files_dir_without_wp_plugin_dir)[$target_folder])</dt><dd>'.explode(DIRECTORY_SEPARATOR, $path_to_this_files_dir_without_wp_plugin_dir)[$target_folder].'</dd>';
echo '<dt class="keyTerms">function get_my_plugin_root_dir()</dt><dd><span class="red">'.get_my_plugin_root_dir().'</span></dd>';

?>
        </section>

        <section id="footer">
            <p class="content footer cite">Based on Notes by <a href="https://github.com/ajaxStardust" target="_blank"
                    title="View original">@ajaxStardust</a> <em>Laravel</em> notes.
            </p>
        </section>
    </div> <!--    .content  -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous">
    </script>
    <script id='contact-form-7-js-extra'>
    var wpcf7 = {
        "api": {
            "root": "http:\/\/10.0.0.38\/ArlingtonFD\/wp-json\/",
            "namespace": "contact-form-7\/v1"
        }
    };
    </script>
    <script src='https://10.0.0.38/ArlingtonFD/wp-content/plugins/contact-form-7/includes/js/index.js?ver=5.7.2'
        id='contact-form-7-js'></script>
</body>

</html>