<?php 
date_default_timezone_set('EST');
$page_heading = 'GetDefinedVars demo';
$title = 'GetDefinedVars demo';
$lastMod = "Modified: " . date("D M j Y G:i:s T", getlastmod());
$localScope[] = '<ul style="list-style-type:upper-roman;">
    ';
$definedVarNames = get_defined_vars(); 

foreach($definedVarNames as $thisKey => $thisValue){ 
if(gettype($thisValue) == 'string'){
        $thisValue = htmlentities($thisValue);
    }
    if($thisKey!=='localScope'){
        // break;
    }


 
if(!is_array($definedVarNames["$thisKey"])){
    $localScope[] = '<li><strong>NOT AN ARRAY:</strong> <span class="keyStyle">$'.
        $thisKey.'</span> = <span class="larger">&#x201c;</span>'. $thisValue .'<span class="larger">&#x201d;</span></li>
            ';
    }
    else    {
//  while($thisKey == '30'){

        /*$localScope[] = '<li class="listheader">'.$thisKey.':
        '.
        '    <ul style="list-style-type:lower-latin;">
        ';*/
        $localScope[] = '<li class="listheader">'.$thisKey.' ';

        foreach($definedVarNames["$thisKey"] as $multiDimTEST_key => $multiDimTEST_val){
            if(is_array($multiDimTEST_val)){
                $localScope[] = '<ul style="list-style-type:upper-latin">
                ';
                foreach($multiDimTEST_val as $multiDim0_key => $multiDim0_val){
                    $localScope[] = '<li>$multiDim0_key[<span class="keyStyle">'.$multiDim0_key.']:</span>: '.$multiDim0_val.'</li>';
                }
                $localScope[] = '</ul>
                ';
            }
            else{
                $localScope[] = ' <br />(<span class="keyStyle">'.$multiDimTEST_key.':</span>) <span class="sansSerif">'.$multiDimTEST_val.'</span>
                ';
            }

        }
        /*
            $localScope[] =  '</li>
        '.
        '</ul>
                ';
        */

        $localScope[] = '</li>
        ';
//  }
}

$localScope[] = '</ul>
    ';
}

?>
<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8"> 
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>
    <?php print $title; ?>
  </title>
  <link rel="icon" type="image/ico" href="favicon.ico">
  <link rel="shortcut icon" type="image/ico" href="favicon.ico">
  <style>
/** if needed add style here */
  </style>
    <link 
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" 
        rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" 
        crossorigin="anonymous">    <!-- BOOTSTRAP STYLE -->
    <link 
        rel="stylesheet" 
        href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link 
        href="https://api.mapbox.com/mapbox-gl-js/v2.1.1/mapbox-gl.css" 
        rel="stylesheet">
    <link 
        href="css/notes.css" 
        rel="stylesheet" 
        type="text/css">
</head>

<body>

  <div id="pagewidth" class="container">
 
    <section id="header">  <!-- #HEADER -->
        <h1 class="bg-dark text-light text-end pe-3"><?php print $page_heading; ?></h1>
    </section>
    <section class="content">
      <div class="notes">                           
       <div class="parchment">
<h1>VS GetDefinedVars.phtml</h1>
<code>$currentUrlPath.$patharray['basename']; == <?php print $currentUrlPath.$patharray['basename']; ?></code>
<p>The Files <code>GetDefinedVarsOrig.phtml</code> and <code>GetDefinedVars.phtml</code> exist for the purpose of reviewing what values are assigned to various local-context PHP variables.<br />Note: <code>GetDefinedVars.phtml</code> attempts to hide any <em>private</em> data, should the developer choose to include it in a production environment, for example for demonstration purposes.</p>
<h2>Origin of Data</h2>
<p>Data shown here is obtained via the PHP built-in function get_defined_vars(), and extracted using a foreach loop after the returned values are assigned to an array-type symbol/ variable. </p>
<blockquote>(i.e. <code>$definedVarNames = get_defined_vars();</code>)</blockquote>
<p><strong>Note:</strong> Html tags which are part of any PHP variable value are rendered as HTML (e.g. the variable shown below, [ $bodyidtxt ], contains the HTML heading tag, &#x3C;H1&#x3E;</p>
<p><strong>See <em>getdefinedvarsorig.phtml</em></strong> for viewing those values which are hidden in this public view. (i.e. to view values more appropriate for <em>development-server</em> viewing)</p>

<?php
foreach($localScope as $localScopePrint) {

    print $localScopePrint;
}
echo '<br />$_SERVER["PHP_SELF"]:<br /><pre>';
echo 'print_r(parse_url($_SERVER["PHP_SELF"]));<br />';
print_r(parse_url($_SERVER['PHP_SELF']));
echo '</pre>';

echo '<br />get_defined_vars:<br /><pre>';
echo 'print_r(get_defined_vars());<br />';
print_r(get_defined_vars());
echo '</pre>';

?>
</div>
      </div>                                        <!--    .notes      -->
    </section>
    <section class="footer px-4">                   <!--    .FOOTER     -->
        <div class="row gx-5">
            <div class="col"><div class="p-3 border bg-light"> Based on Notes by <a href="https://github.com/ajaxStardust" target="_blank" title="View original">@ajaxStardust</a> <em>Laravel</em> notes:</div></div>
            <div class="col"><div class="p-3 border bg-light text-end"><kbd><?php echo $lastMod; ?></kbd></div></div>
        </div>
    </section>      
  </div>                                            <!--    .content  -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
</body>
</html>