<?php 

error_reporting(E_STRICT);
date_default_timezone_set('EST');
$page_heading = 'Graphic Design Stuff by J.S.';
$title = 'Graphic Design Stuff by J.S.';
$lastMod = "Modified: " . date("D M j Y G:i:s T", getlastmod());
/**
*  @method frame_only
 * @param ENUM (TRUE,FALSE)
 * @abstract
 *  use frame_only() to force the document into preferred frame, relative to project.
 *
 */

?>
<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8"> 
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>
    <?php print $title; ?>
  </title>
  <link rel="icon" type="image/ico" href="favicon.ico">
  <link rel="shortcut icon" type="image/ico" href="favicon.ico">
    <style type="text/css">
        .carousel-inner {
            height: 300px;
        }
    </style>
    <link 
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" 
        rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" 
        crossorigin="anonymous">    <!-- BOOTSTRAP STYLE -->
    <link 
        rel="stylesheet" 
        href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link 
        href="https://api.mapbox.com/mapbox-gl-js/v2.1.1/mapbox-gl.css" 
        rel="stylesheet">
    <link 
        href="css/notes.css" 
        rel="stylesheet" 
        type="text/css">
</head>

<body>

  <div id="pagewidth" class="container">
 
    <section id="header">  <!-- #HEADER -->
        <h1 class="bg-dark text-light text-end pe-3">h1 - Demonstrating Basic Bootstrap CSS Styles</h1>
    </section>
 
 
            <p>p</p>
            <h2>
                h2
            </h2>


            <ul>
                <li>ul list item
                </li>
                <li>ul list item
                </li>
            </ul>
            <h3>
                h3
            </h3>
            <ol>
                <li>ol list item
                </li>
                <li>ol list item
                </li>
            </ol>
            <h4>
                h4
            </h4>
            <div class="container"> div.container
                <dl>
                    <dt>
                        dt - Definition Title
                    </dt>
                    <dd class="m-4">
                        DD - def data - this DL is child of div.container
                    </dd>
                </dl>
            </div>
            <h5>
                h5
            </h5>
            <div class="container-md row">
                <table class="col w-75">
                    <caption>
                        Table Caption
                    </caption>
                    <thead>
                        <tr class="border">
                            <th class="col bg-primary text-light p-1 text-center border">
                                Table Thead - TH
                            </th>
                            <th class="col bg-primary text-light p-1 text-center border">
                                Table Thead - TH
                            </th>
                            <th class="col bg-primary text-light p-1 text-center border">
                                Table Thead - TH
                            </th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <td>
                                Tfoot - TD
                            </td>
                            <td>
                                Tfoot - TD
                            </td>
                            <td>
                                Tfoot - TD
                            </td>
                        </tr>
                    </tfoot>
                    <tbody>
                        <tr>
                            <td>
                                TR > TD - table row data
                            </td>
                            <td>
                                TD - table row data
                            </td>
                            <td>
                                TD - table row data < TR </td>
                        </tr>
                        <tr>
                            <td>
                                TR > TD - table row data
                            </td>
                            <td>
                                TD table row data
                            </td>
                            <td>
                                TD table row data < TR </td>
                        </tr>
                        <tr>
                            <td>
                                TR > TD - table row data
                            </td>
                            <td>
                                TD table row data
                            </td>
                            <td>
                                TD table row data < TR </td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <h6>
                h6
            </h6><code>code</code>
            <pre class="bg-dark text-light">\n
pre \n
\n
\n
    </pre>
        </div>

    <section class="footer px-4">                   <!--    .FOOTER     -->
        <div class="row gx-5">
            <div class="col"><div class="p-3 border bg-light"> Based on Notes by <a href="https://github.com/ajaxStardust" target="_blank" title="View original">@ajaxStardust</a> <em>Laravel</em> notes:</div></div>
            <div class="col"><div class="p-3 border bg-light text-end"><kbd><?php echo $lastMod; ?></kbd></div></div>
        </div>
    </section>      
  </div>                                            <!--    .content  -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
</body>
</html>