<?php
/*
 * adb_simplest/template.phtml
 *
 * Copyright 2023 @ajaxStardust <flux@mx23>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301, USA.
 *
 *
 */

header('Access-Control-Allow-Origin: *'); // ENABLE CORS (Cross-Origin Request) policy allow all - CAUTION: not-ready-for-prime-time player
date_default_timezone_set('EST');

function process_tree_json(){

    $tree_json = [];
    $tree_json['config_file'] = './tree.json';
    $tree_json['config_data'] = file_get_contents($tree_json['config_file']);

    // ['config_data'] becomes stdClass here
    $tree_json['config_data'] = json_decode($tree_json['config_data'] );
    // $tree_json['config_data'] = json_encode( $tree_json['config_data'] ) ;

    return $tree_json;
}

$tree_json_out = process_tree_json();
/*echo '<br>var_dump(tree_json_out): '.var_dump($tree_json_out) .'<br>';
echo '<br>print_r(tree_json_out): ' .print_r($tree_json_out) .'<br>';*/
$confdata = '<ul id="config_data">';
foreach ($tree_json_out['config_data']->errors as $key => $value) {
    $confdata .= '<li class="json_data">'.$key.': '.$value.'</li>';
    print "\n<br>".$key.": ".$value."\n<br>";
}
foreach ($tree_json_out['config_data']->files as $key => $value) {

    // var_dump($value['errors']);
    // var_dump($value['messages']->message);
    $jsonenval = json_encode($value['errors']);
    // $jsondeval = json_decode($value);
    $confdata .= '<li class="json_data">'.$key.': '.$jsonenval.'</li>';

}
$confdata .= '</ul>';
echo '<br>this is cd_html: '. $confdata .'<br>';

if (!defined('ADBLOCTN')) {
    define('ADBLOCTN', rtrim(dirname(__FILE__), 'public/inc'));
}
$abspath = ADBLOCTN;

$http_type = $_SERVER['SERVER_SOFTWARE'];
$http_name = $_SERVER['SERVER_NAME'];
$http_ip = $_SERVER['SERVER_ADDR'];
$httpname = $http_name;
if (preg_match('@(10\.0\.0\.\d+|192\.\d+\.\d+\.\d+)@', $http_ip)) {
    $abspath = '<code class="info">' . $abspath . '</code>';
} else {
    $abspath = 'is simply a PHP value which relies on server variables<code>define( ADBLOCTN , rtrim(dirname(__FILE__), inc))</code>';
}

$parent_dir = str_ireplace('/var/www/html','',__DIR__);

$page_heading = '&#x201c;Simple Template&#x201d;';
if($page_heading == '&#x201c;Simple Template&#x201d;'){
$real_page_heading = pathinfo(__FILE__, PATHINFO_FILENAME);
}
else {
$real_page_heading = $page_heading;
}

$title = $http_ip.' - '.$parent_dir.' - EditPlus_IV TEMPLATE';
$lastMod = "Modified: " . date("D M j Y G:i:s T", getlastmod());

?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="msapplication-TileImage" content="favicon.webp">
    <title>
        <?php print $title; ?>
    </title>
    <link rel="icon" type="image/ico" href="favicon.ico" sizes="16x16">
    <link rel="shortcut icon" type="image/webp" href="favicon.webp">
    <link rel="icon" href="favicon.ico" sizes="32x32">
    <link rel="icon" href="favicon.ico" sizes="192x192">
    <link rel="apple-touch-icon" href="favicon.webp">


    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- BOOTSTRAP STYLE -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link href="assets/css/notes.css" rel="stylesheet">
    <style>
    .tsw {
        font-family: "roboto";
        font-size: 1.2rem;
        font-style: italic;
    }
    .S0 {
        font-family: "roboto mono";
        font-size: 10pt;
        font-style: italic;
    }
   .S1 {
        font-family: "roboto mono";
        color: #000080;
        font-size: 10pt;
    }
    </style>
</head>

<body>

    <div id="pagewidth" class="container">
        <!--    :begin    class:content        -->

        <section id="header">
            <!-- #HEADER -->
            <h1 class="bg-dark text-light text-end pe-3">
                <?php print $real_page_heading; ?>
            </h1>
        </section>
        <section id="general_notes">
            <h2>General Notes</h2>
            <div class="notes">
                <!-- ADD NOTES HERE -->




            </div> <!-- $ end .notes div -->
        </section>
        <section>
            <!-- :begin #_GLOSSARY  -->
            <div>
                <h2>Further Reading</h2>
                <h3><?php print $real_page_heading; ?> - Glossary</h3>

                <p class="pseudocite">Famous Last Words</p>
            </div> <!-- $ :end #_glossary -->
        </section>
        <footer class="footer px-4">
            <!--    .FOOTER     -->
            <div class="row gx-5">
                <div class="col">
                    <div class="p-3 border bg-light"> Based on Notes by <a href="https://github.com/ajaxStardust"
                            target="_blank" title="View original">@ajaxStardust</a> <em>Laravel</em> notes:</div>
                </div>
                <div class="col">
                    <div class="p-3 border bg-light text-end"><kbd>
                            <?php echo $lastMod; ?>
                        </kbd></div>
                </div>
            </div>
        </footer>
    </div><!--    $ :end    END class.content (former id.maincol)    $    -->

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous">
    </script>
    <script src="assets/js/showme-hideme.js"></script>

</body>

</html>
