<?php

$title = 'CSS Grid Notes from Brenda Storer';
$h1 = 'CSS Grid Notes from <a href="https://brendastorer.com/" target="_blank">Brenda Storer</a>';
if($title == ''){
  $title = 'DONT FORGET THE TITLE!';
}

?>

<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8">
  <meta http-equiv="Content-Style-Type" content="text/css" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $title; ?></title>
    
  <style><!--/*--><![CDATA[/*> custom style here if needed <!--*/
      .search-results {
display: grid;
grid-gap: 10px;
grid-template-columns: repeat(auto-fit, minmax(320px, 1fr));
padding: 10px;
}
/*]]>*/--></style>

<!--    <link 
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" 
        rel="stylesheet" 
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" 
        crossorigin="anonymous">
    <link 
        rel="stylesheet" 
        href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link 
        href="https://api.mapbox.com/mapbox-gl-js/v2.1.1/mapbox-gl.css" 
        rel="stylesheet">-->
    <link 
        href="assets/css/notes.css" 
        rel="stylesheet" 
        type="text/css" 
        media="screen">
    <link 
       href="assets/css/grid_notes2.css"
       rel="stylesheet">
</head>
<body>

<div id="pagewidth" class="container">

<section id="header">  
    <h1 class="bg-dark text-light text-end pe-3"><?php echo $h1; ?></h1>
</section>

<section id="primary">
    <div class="notes"> <!-- ^:begin https://www.heartinternet.uk/blog/fearless-guide-using-css-grid-today/ notes ^ -->
    <p> notes from:<br>
    https://www.heartinternet.uk/blog/fearless-guide-using-css-grid-today/</p>
<div class="container">
<ul class="search-results">
<li class="search-results__result">
<img class="search-results__photo" src="path-to-image.jpg">
</li>
<li class="search-results__result">
<img class="search-results__photo" src="path-to-image.jpg">
</li>
    <li class="search-results__result">
<img class="search-results__photo" src="path-to-image.jpg">
</li>
    <li class="search-results__result">
<img class="search-results__photo" src="path-to-image.jpg">
</li>
    <li class="search-results__result">
<img class="search-results__photo" src="path-to-image.jpg">
</li>
    <li class="search-results__result">
<img class="search-results__photo" src="path-to-image.jpg">
</li>
    <li class="search-results__result">
<img class="search-results__photo" src="path-to-image.jpg">
</li>
    <li class="search-results__result">
<img class="search-results__photo" src="path-to-image.jpg">
</li>
    <li class="search-results__result">
<img class="search-results__photo" src="path-to-image.jpg">
</li>
    <li class="search-results__result">
<img class="search-results__photo" src="path-to-image.jpg">
</li>
</ul>
 
</div>
    </div>
</section>

<section id="secondary">
    <div class="glossary"> <!-- ^:begin #angular_GLOSSARY ^ -->
    <h2>Glossary:</h2>
    <dl class="glossary-main">
        <dt>Def Title...</dt>
        <dd>Def Data...
        <pre>#       /var/www/html/app-project-folder/
#       |-- some.file
#       |-- other.ts
#       |-- yetmore.json
#       |-- files.js</pre>
        </dd>
    </dl>
    </div> <!-- $   #glossary   -->
</section>

<section id="fooder">
    <p class="content footer cite">Notes Template by <a href="https://github.com/ajaxStardust" target="_blank" title="View original">@ajaxStardust</a> - Visit his GitHub
    </p>
</section>

</div><!-- #pagewidth .container -->

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>

</body>
</html>
