<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8">
  <meta http-equiv="Content-Style-Type" content="text/css" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>
    Tutorial - My Notes
  </title>
  <link href="iframestyle.css" rel="stylesheet" type="text/css" media="screen" />
  <style>
    #_notes_dl dt {
      text-transform: uppercase;
      font-weight: bold;
      /* border-right:           9pt solid #e5e5e5; */
      border-left:           4pt solid #F9322C;
      padding-left: 1em;
    }

    #_notes_dl dd dl dt {
        /* border-right:           6pt solid #e5e5e5; */
        border-left:           6pt solid #e5e5e5;
    }

    dl dd {
      margin: 1em 0 2em 2em;
    }

    .dd_div {
      margin: 0.5em;
    }

    .code {
      background-color: #101010;
      color: #F0F0F9;
      padding: 0.5em;
      white-space: pre-wrap;
    }

    .code:before {
      content: 'user@laragigs $> ';
      color:lawngreen;
    }
    h2 {
        border-right-width: 1pt;
    }
    h3 {
        border-right: 0;
    }
    .content code {
        background-color: #EAEAEA;
    }
  </style>
  	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous" />
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css" />
	<link href="https://api.mapbox.com/mapbox-gl-js/v2.1.1/mapbox-gl.css" rel="stylesheet" />
</head>

<body>
  <!--    ^:begin    id:pagewidth    ^    -->
  <section id="pagewidth" class="container">

    <!--    ^:begin    class:content    ^    -->
    <div class="">
    <section id="header">  
    <h1 class="bg-dark text-light text-end pe-3"> Notes -  Tutorial</h1>
</section>
<section id="general_notes">
      <div id="" class="notes"> <!-- ^:begin #general_notes ^ -->
        <h2>General Notes</h2>
        <p>Some note here...</p>
</section>
      <div id="_glossary"> <!-- ^:begin #_GLOSSARY ^ -->
        <h2>Glossary:</h2>
        <dl id="_notes_dl">
            <dt id="routing"> Def Title...</dt>
            <dd>Something about  folder structure...
                <pre>#       /var/www/html/framework_name/
#       |-- some.file
#       |-- some.ts
#       |-- some.json
#       |-- some.js</pre>

        </dl>
        </div> <!-- $ :end #_glossary -->
        <p class="content footer cite">Based on Brad Traversy&apos;s <a href="https://github.com/bradtraversy/-crash-2021" target="_blank" title="View original"></a> Crash Course.
        </p>
      </div><!--    $ :end    END class.content (former id.maincol)    $    -->
  </section>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
</body>

</html>

