<?php 
date_default_timezone_set('EST');
$page_heading = 'GitHub Notes - GIT Version Control';
$title = 'GIT notes';
$lastMod = "Modified: " . date("D M j Y G:i:s T", getlastmod());
?>
<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8"> 
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>
    <?php print $title; ?>
  </title>
  <link rel="icon" type="image/ico" href="favicon.ico">
  <link rel="shortcut icon" type="image/ico" href="favicon.ico">
  <style>
/** if needed add style here */
  </style>
    <link 
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" 
        rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" 
        crossorigin="anonymous">    <!-- BOOTSTRAP STYLE -->
    <link 
        rel="stylesheet" 
        href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link 
        href="https://api.mapbox.com/mapbox-gl-js/v2.1.1/mapbox-gl.css" 
        rel="stylesheet">
    <link 
        href="assets/css/notes.css" 
        rel="stylesheet" 
        type="text/css">
</head>

<body>

  <div id="pagewidth" class="container">
 
    <section id="header">  <!-- #HEADER -->
        <h1 class="bg-dark text-light text-end pe-3"><?php print $page_heading; ?></h1>
    </section>

</section>
<section id="general_notes" class="container"> 
      <div id="" class="notes"> <!-- ^:begin #general_notes ^ -->
        <h2>Add new local code to Git repo</h2>
       <p>How to Initialize the local directory as a Git repository</p>   
        </div>
</section>    
<section class="container">
<div>

<pre><code># Initialize the local directory as a Git repository.
git init

# Add files
git add .

# Commit your changes
git commit -m "First commit"

# Add remote origin
git remote add origin &lt;Remote repository URL&gt;
# &lt;Remote repository URL&gt; looks like: https://github.com/user/repo.git

# Verifies the new remote URL
git remote -v

# Push your changes
git push origin master
</code></pre>
<dl>
<dt>roundabout</em> way of achieving same effect:</dt>
<dd><ul>
<li>Clone git repo</li>
<li>Copy and paste into it</li>
<li>Push your change at origin</li>
</ul>
<p>If in any case git reject your push you can use <code>git push origin master --force</code></dd>
</dl><!-- $ :end #_glossary -->  
</div>      
</section>                               
<section id="footer">
        <p class="content cite">(Section#footer.container > p ) Notes Template by <a href="https://github.com/ajaxStardust" target="_blank" title="View original">@ajaxStardust</a>. {date}
        </p> 
</section>
      </div><!--    $ :end    END class.content (former id.maincol)    $    -->
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
</body>

</html>

