<?php
header('Access-Control-Allow-Origin: *'); // ENABLE CORS (Cross-Origin Request) policy allow all
date_default_timezone_set('EST');
$page_heading = 'WordPress Test Quicklet';
$title = 'nnxiola on mx23 quicklets';
$lastMod = "Modified: " . date("D M j Y G:i:s T", getlastmod());

if( file_exists('/var/www/html/wpc_cpts/wp-config.php'))   {
include '/var/www/html/wpc_cpts/wp-config.php';
}

function get_my_plugin_root_dir()
{

  $path_to_this_files_dir_without_wp_plugin_dir = str_replace(WP_PLUGIN_DIR, '', __DIR__);


  $file_depth = preg_replace('@([\x5c\x2f])@', '/', __FILE__);
  $solidus_count = substr_count($file_depth, "/");
  $target_folder = $solidus_count - 3;
  $plugin_directory_name_only = explode(DIRECTORY_SEPARATOR, $path_to_this_files_dir_without_wp_plugin_dir)[$target_folder];


  return WP_PLUGIN_DIR . DIRECTORY_SEPARATOR . $plugin_directory_name_only;
}

$file_depth = preg_replace('@([\x5c\x2f])@', '/', __FILE__);
$solidus_count = substr_count($file_depth, "/");
$target_folder = $solidus_count - 3;

$path_to_this_files_dir_without_wp_plugin_dir = str_replace(WP_PLUGIN_DIR, '', __DIR__);
$plugin_directory_name_only = explode(DIRECTORY_SEPARATOR, $path_to_this_files_dir_without_wp_plugin_dir)[$target_folder];

?>
<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>
    <?php print $title; ?>
  </title>
  <link rel="icon" type="image/ico" href="/favicon.ico">
  <link rel="shortcut icon" type="image/ico" href="/favicon.ico">

  <style>

.tsw {
    font-family: "source serif pro";
    font-size: 1.2rem;
    font-style: italic;
}
.displaynone {
  display:none;
}
.prewrap {
  white-space: pre-wrap;
}

.unicodefont {
  font-family: Roboto, Poppins, "Noto Sans", "DejaVu Sans";
}

                /** if needed add style here
                ** NOTE THE NEW favICON code here:
                **
                */
  </style>
    <link rel="icon" href="/favicon.ico">
    <link rel="icon" href="/favicon.ico" sizes="192x192">
    <link rel="apple-touch-icon" href="/favicon.ico">
    <meta name="msapplication-TileImage" content="/favicon.ico">


    <link
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
        rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x"
        crossorigin="anonymous">    <!-- BOOTSTRAP STYLE -->
    <link
        rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link
        href="https://api.mapbox.com/mapbox-gl-js/v2.1.1/mapbox-gl.css"
        rel="stylesheet">
    <link
        href="<?php echo get_theme_root_uri(); ?>/css/bs.blog.css"
        rel="stylesheet">
    <link
        href="<?php echo get_theme_root_uri(); ?>/css/notes.css"
        rel="stylesheet">
</head>

<body>

  <div id="pagewidth" class="container">    <!--    ^:begin    class:content    ^    -->

    <section id="header">  <!-- #HEADER -->
        <h1 class="bg-dark text-light text-end pe-3 blog-header-logo text-light"><?php print $page_heading; ?></h1>
    </section>
    <section id="general_notes">
          <div class="notes"> <!-- ^:begin #general_notes ^ -->
            <h2 class="text-center">Quicklet Temp pHTML <span class="unicodefont">&#x01f12f;</span></h2>
            <div class="notes">
                                        <!-- ADD NOTES HERE --><!-- ADD NOTES HERE -->
                <dl>
                  <dt class="keyTerms pointer">Example Collapse <span class="normal blue pointer" id="show_n01" onclick="swap_text('show_n01','notes_01') ">[toggle...]</span>
                </dt>
                    <dd id="notes_01" class="displaynone"> <!-- hidden then revealed -->
                      <p>For the array in
                        <code>register_post_type('custom-type-name', <strong>[ 'has_archive' => true, 'public' => true, etc => blahblah ]</strong>')</code>
                      place the php exported by ACF or CPT UI, or whatever means used to create the custom post type (e.g. manually entered).</p>
                          <pre>
function register_form_log_post_type() {
    register_post_type('form_log', array(
        'labels' => array(
            'name' => __('Form Logs'),
            'singular_name' => __('Form Log')
        ),
        'public' => true,
        'has_archive' => true,
        'supports' => array('title', 'editor'),
    ));
}
add_action('init', 'register_form_log_post_type');
                      </pre>
                    </dd>

                  <dt class="keyTerms pointer">My get_option() Display function: <span class="normal blue pointer" id="show_n02" onclick="swap_text('show_n02','notes_02') ">[toggle...]</span>
                </dt>
                    <dd id="notes_02" class="displaynone"> <!-- hidden then revealed -->
                      <?php
                      function test_get_options(){
                        echo '<div><h2>Demo of WP Native funcs:</h2>'.
                        '<code>get_template_directory_uri():'.get_template_directory_uri().'</code><br>
                        <code><strong>get_theme_root_uri(): '.get_theme_root_uri().'</strong></code><br>
                        <pre class="prewrap">get_option("home"): '.get_option("home").'
get_option("admin_email"): '.get_option("admin_email").'
get_option("blogname"): '.get_option("blogname").'
get_option("blogdescription"): '.get_option("blogdescription").'
get_option("blog_charset"): '.get_option("blog_charset").'
get_option("date_format"): '.get_option("date_format").'
get_option("default_category"): '.get_option("default_category").'
get_option("home"): '.get_option("home").'
get_option("posts_per_page"): '.get_option("posts_per_page").'
get_option("posts_per_rss"): '.get_option("posts_per_rss").'
get_option("siteurl"): '.get_option("siteurl").'
get_option("template"): '.get_option("template").'
get_option("start_of_week"): '.get_option("start_of_week").'
get_option("upload_path"): '.get_option("upload_path").'
get_option("users_can_register"): '.get_option("users_can_register").'
get_bloginfo("url"): '.get_bloginfo( 'url' ).'
get_bloginfo("wpurl"): '.get_bloginfo( 'wpurl' ).'
                        </pre>';
                        }
                      add_action('admin_menu', 'test_get_options');
                      test_get_options();
                      ?>
                    </dd>
                </dl>

                                        <!-- ADD NOTES HERE --><!-- ADD NOTES HERE -->

            </div>
          </div>                    <!-- $ end .notes div -->
    </section>

      <section class="footer px-4">                   <!--    .FOOTER     -->
        <div class="row gx-5">
            <div class="col"><div class="p-3 border bg-light"> Based on Notes by <a href="https://github.com/ajaxStardust" target="_blank" title="View original">@ajaxStardust</a>: now a <em>WordPress</em> Quicklet:</div></div>
            <div class="col"><div class="p-3 border bg-light text-end"><kbd><?php echo $lastMod; ?></kbd></div></div>
        </div>
    </section>
      </div><!--    $ :end    END class.content (former id.maincol)    $    -->
  </section>
            </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
                <script src="<?php echo get_theme_root_uri(); ?>/js/showme-hideme.js"></script>

</body>

</html>

