<?php 
date_default_timezone_set('EST');
$page_heading = 'WordPress native "get_" functions';
$title = 'WordPress get_ functions';
$lastMod = "Modified: " . date("D M j Y G:i:s T", getlastmod());
?>
<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8"> 
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>
    <?php print $title; ?>
  </title>
  <link rel="icon" type="image/ico" href="favicon.ico">
  <link rel="shortcut icon" type="image/ico" href="favicon.ico">
  <style>
/** if needed add style here */
  </style>
    <link 
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" 
        rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" 
        crossorigin="anonymous">    <!-- BOOTSTRAP STYLE -->
    <link 
        rel="stylesheet" 
        href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link 
        href="https://api.mapbox.com/mapbox-gl-js/v2.1.1/mapbox-gl.css" 
        rel="stylesheet">
    <link 
        href="assets/css/notes.css" 
        rel="stylesheet" 
        type="text/css">
</head>

<body>

  <div id="pagewidth" class="container">
 
    <section id="header">  <!-- #HEADER -->
        <h1 class="bg-dark text-light text-end pe-3"><?php print $page_heading; ?></h1>
    </section>
    <section class="content">
      <div class="notes">                           
        <pre>get_ancestors();
get_archives_link();
get_attached_file();
get_attached_media();
get_attached_media_args();
get_available_languages();
get_avatar();
get_avatar_comment_types();
get_avatar_data();
get_avatar_url();
get_block_file_template();
get_block_template();
get_block_templates();
get_bloginfo_rss();
get_blogs_of_user();
get_bookmarks();
get_calendar();
get_canonical_url();
get_categories_taxonomy();
get_comment();
get_comments_link();
get_comments_number();
get_comments_pagenum_link();
get_comment_author();
get_comment_author_email();
get_comment_author_IP();
get_comment_author_link();
get_comment_author_url();
get_comment_author_url_link();
get_comment_date();
get_comment_excerpt();
get_comment_ID();
get_comment_link();
get_comment_text();
get_comment_time();
get_comment_type();
get_custom_logo();
get_custom_logo_image_attributes();
get_date_sql();
get_default_comment_status();
get_delete_post_link();
get_editable_authors();
get_edit_bookmark_link();
get_edit_comment_link();
get_edit_post_link();
get_edit_tag_link();
get_edit_term_link();
get_edit_user_link();
get_enclosed();
get_feed_build_date();
get_footer();
get_header();
get_header_image_tag();
get_header_image_tag_attributes();
get_header_video_url();
get_image_tag();
get_image_tag_class();
get_lastpostdate();
get_lastpostmodified();
get_main_network_id();
get_media_item_args();
get_meta_sql();
get_network();
get_object_subtype_();
get_object_terms();
get_others_drafts();
get_pagenum_link();
get_pages();
get_page_of_comment();
get_page_of_comment_query_args();
get_page_uri();
get_post_galleries();
get_post_gallery();
get_post_modified_time();
get_post_status();
get_post_time();
get_pung();
get_role_list();
get_sample_permalink();
get_sample_permalink_html();
get_schedule();
get_search_form();
get_search_query();
get_shortlink();
get_sidebar();
get_site();
get_site_icon_url();
get_space_allowed();
get_tags();
get_template_part();
get_template_part_();
get_term();
get_terms();
get_terms_args();
get_terms_defaults();
get_terms_fields();
get_terms_orderby();
get_theme_starter_content();
get_the_archive_description();
get_the_archive_title();
get_the_archive_title_prefix();
get_the_author_();
get_the_categories();
get_the_date();
get_the_excerpt();
get_the_generator_();
get_the_guid();
get_the_modified_date();
get_the_modified_time();
get_the_post_type_description();
get_the_tags();
get_the_terms();
get_the_time();
get_to_ping();
get_usernumposts();
get_users_drafts();
get_user_option_();
get_wp_title_rss();</pre>
      </div>                                        <!--    .notes      -->
    </section>
    <section class="footer px-4">                   <!--    .FOOTER     -->
        <div class="row gx-5">
            <div class="col"><div class="p-3 border bg-light"> Based on Notes by <a href="https://github.com/ajaxStardust" target="_blank" title="View original">@ajaxStardust</a> <em>Laravel</em> notes:</div></div>
            <div class="col"><div class="p-3 border bg-light text-end"><kbd><?php echo $lastMod; ?></kbd></div></div>
        </div>
    </section>      
  </div>                                            <!--    .content  -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
</body>
</html>