<?php
/**
 * @method frame_only
 * @param ENUM (TRUE,FALSE)
 * @abstract
 * 	use frame_only() to force the document into preferred frame, relative to project.
 *
*/
/*require 'public/class/class-adbfuncs.php';
frame_only(TRUE);*/

/*
**     NOTE: THIS DOCUMENT IS DECLARED AS HTTP-EQUIV(Content-Type) "application/xml-html"
**     IF YOUR SERVER CONFIGURATION (i.e. .conf, .htaccess, php.ini, etc.) is set to
**    parse HTML as XHTML (i.e. XML), in a strict manner, this document may not display,
**     instead, rendering as bad XML markup. In its original form, the XHTML below
**     should NOT cause a server error, but "never" is a heavy word in this business. ;-)
**
**    The recommended Content-type for the WWW as of 2009 is "text/html",
**    albeit such use is a direct contradiction of the very philosophy of XHTML.
*/
print '<?xml version="1.0" encoding="utf-8"?>
';
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <title>
            frame_only() :: class/class-adbfuncs.php try forcing this.document into proj relative frame path
        </title>
        <meta http-equiv="Content-Style-Type" content="text/css" />
        <meta http-equiv="content-type" content="application/xhtml+xml; charset=utf-8" />
        <script type="text/javascript" src="assets/js/iframestuff.js">
</script>
        <link href="assets/css/iframestyle.css" rel="stylesheet" type="text/css" media="screen" />
    </head>
    <body>
        <!--    ^    id#pagewidth    ^    -->
        <div id="pagewidth">
            <!--    ^    class.content    ^    -->
            <div class="content">
			<h1>Managing APT PPA Data via Terminal Command Line</h1>
                <h2>Add a PPA using the Terminal</h2>
<div>
Basically, the command to add PPA on terminal is "<strong>sudo add-apt-repository ppa:NAMEOFPPA</strong>".
 After adding PPA, you need to update the list of application. Without
this action, the added PPA will not be registered on the system.&nbsp;</div>
<div>
<br />
<table border="1" cellpadding="4" cellspacing="0"><tbody>
<tr><td><strong class="code terminal"># ~ sudo add-apt-repository ppa:PPANAME</strong><br />
<strong class="code terminal"># ~ sudo apt-get update</</strong></td></tr>
</tbody></table>
<br /></div>
<strong>Sample:&nbsp;</strong><br />
sudo add-apt-repository ppa:tualatrix/ppa<br />
sudo apt-get update<br />
sudo apt-get install ubuntu-tweak<br />
<h2>Remove a PPA</h2>
Removing
 PPA means that you remove the repository of application from the
software source on the computer. The application you've installed from
the PPA is still available on the system. Removing the PPA doesn't mean
removing the application.<br />
<br />
Basically, the command to remove "<strong>sudo add-apt-repository --remove ppa:PPANAME</strong>". You have to insert the name off PPA you've registered on the software source.<br />
<br />
<div>
<br />
<table border="1" cellpadding="4" cellspacing="0"><tbody>
<tr><td><strong class="code terminal"># ~ sudo add-apt-repository --remove ppa:PPANAME</strong><br />
<strong class="code terminal"># ~ sudo apt-get update</strong></td></tr>
</tbody></table>
<br /></div>
<strong>Sample: </strong><br />
&nbsp;sudo add-apt-repository --remove ppa:tualatrix/ppa<br />
<br />
<br />
<h2>Purge a PPA</h2>
To purge PPA you need to install PPA-purge command line. To install it, run this command:<br />
<div>
<br />
<table border="1" cellpadding="4" cellspacing="0"><tbody>
<tr><td><strong class="code terminal"># ~ </strong>sudo apt-get install ppa-purge</td></tr>
</tbody></table>
<br /></div>
Once you installed this command
line, you will be able to use it for purging PPA.&nbsp; Purging PPA doesn't
mean to disable the PPA only. Running this command means that you
downgrade the application you upgraded it using the purged PPA. When you
 run this command to the specific application, the system will
automatically downgrade the application based on the available source on
 the official repository.<br />
<br />
The basic command for purging PPA is "<strong>sudo ppa-purge ppa:PPANAME</strong>". You must insert the correct PPA name on this command.<br />
<br />
Sample:<br />
<div>
<br />
<table border="1" cellpadding="4" cellspacing="0"><tbody>
<tr><td><strong class="code terminal">sudo ppa-purge ppa:PPANAME</strong></td></tr>
</tbody></table>
<br />
<strong>Sample:</strong> </div>
<br />
sudo ppa-purge<strong> </strong>ppa:tualatrix/ppa
            </div>
															<!--    $    .content    $    -->
        </div>
															<!--    $   #pagewidth    $    -->
    </body>
															<!-- 	$	_BODY_	$	-->
															<!--	$	_HTML_	$	-->
</html>
