<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8">
  <meta http-equiv="Content-Style-Type" content="text/css" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>
    Tutorial - My Notes
  </title>
  <link href="iframestyle.css" rel="stylesheet" type="text/css" media="screen" />
  <style>
/** if you need custom styles put it here */
  </style>
  	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous" />
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css" />
	<link href="https://api.mapbox.com/mapbox-gl-js/v2.1.1/mapbox-gl.css" rel="stylesheet" />
</head>

<body>
  <!--    ^:begin    id:pagewidth    ^    -->
  <section id="pagewidth" class="container">

    <!--    ^:begin    class:content    ^    -->
    <div class="">
    <section id="header">  
    <h1 class="bg-dark text-light text-end pe-3"> Notes -  Tutorial</h1>
</section>
<section id="general_notes">
      <div id="" class="notes"> <!-- ^:begin #general_notes ^ -->
        <h2>General Notes</h2>
        <p>Some note here...</p>
</section>
      <div id="_glossary"> <!-- ^:begin #_GLOSSARY ^ -->
        <h2>Glossary:</h2>
        <dl id="_notes_dl">
            <dt id="routing"> Def Title...</dt>
            <dd>Something about  folder structure...
                <pre>#       C:/xampp/htdocs/smsgroupnotify/wp-content/plugins/sms-notify-groups
#       |-- sms-notify-groups.php 
#       |-- ./admin/class-sms-notify-groups-admin.php
#       |-- ./admin/partials/sms-notify-groups-admin-display.php
#       |   ./includes/{index.php, class-sms-notify-groups-{activator,deactivator,i18n,loader}.php}
#       |-- ./includes/class-sms-notify-groups.php
#       |-- ./twiliosdk
#       |-- 
#       |-- 

        </dl>
        </div> <!-- $ :end #_glossary -->
        <p class="content footer cite">Based on Directory Structure as of &apos;s <a href="https://github.com/ajaxStardust" target="_blank" title="View original">2022.10.15</a>, a Saturday afternoon.
        </p>
      </div><!--    $ :end    END class.content (former id.maincol)    $    -->
  </section>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
</body>

</html>

