<?php
/*
 * adb_simplest/template.phtml
 *
 * Copyright 2023 @ajaxStardust <flux@mx23>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301, USA.
 *
 *
 */

header('Access-Control-Allow-Origin: *'); // ENABLE CORS (Cross-Origin Request) policy allow all - CAUTION: not-ready-for-prime-time player
date_default_timezone_set('EST');

if (!defined('ABSOLUTELOCATION')) {
    define('ABSOLUTELOCATION', rtrim(dirname(__FILE__), 'public/inc'));
}
$abspath = ABSOLUTELOCATION;

$http_type = $_SERVER['SERVER_SOFTWARE'];
$http_name = $_SERVER['SERVER_NAME'];
$http_ip = $_SERVER['SERVER_ADDR'];
$httpname = $http_name;
if (preg_match('@(10\.0\.0\.\d+|192\.\d+\.\d+\.\d+)@', $http_ip)) {
    $abspath = '<code class="info">' . $abspath . '</code>';
} else {
    $abspath = 'is simply a PHP value which relies on server variables<code>define( ABSOLUTELOCATION , rtrim(dirname(__FILE__), inc))</code>';
}

$parent_dir = str_ireplace('/var/www/html','',__DIR__);

$page_heading = '&#x201c;Simple Template&#x201d; ';
$title = $http_ip.' - '.$parent_dir.' - EditPlus_IV TEMPLATE';
$lastMod = "Modified: " . date("D M j Y G:i:s T", getlastmod());

?>
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>
    <?php print $title; ?>
  </title>
  <link rel="icon" type="image/ico" href="favicon.ico" sizes="16x16">
  <link rel="shortcut icon" type="image/ico" href="favicon.ico">
  <link rel="icon" href="./favicon.ico" sizes="32x32">
  <link rel="icon" href="./favicon.ico" sizes="192x192">
  <link rel="apple-touch-icon" href="./favicon.ico">
  <meta name="msapplication-TileImage" content="http://.file./ -->">


  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
  <!-- BOOTSTRAP STYLE -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
  <link href="https://api.mapbox.com/mapbox-gl-js/v2.1.1/mapbox-gl.css" rel="stylesheet">
  <link href="assets/css/notes.css" rel="stylesheet" type="text/css">
    <style>
    <![CDATA[
    .tsw {
      font-family: "source serif pro";
      font-size: 1.2rem;
      font-style: italic;
    }

    /** if needed add style here
                                ** NOTE THE NEW favICON code here:
                                **
                                */
  </style>
</head>

<body>

  <div id="pagewidth" class="container"> <!--    :begin    class:content        -->

    <section id="header"> <!-- #HEADER -->
      <h1 class="bg-dark text-light text-end pe-3">
        <?php print $page_heading; ?>
      </h1>
    </section>
    <section id="general_notes">
      <h2>General Notes</h2>
      <div class="notes">
        <!-- ADD NOTES HERE --><!-- ADD NOTES HERE -->
        <!-- ADD NOTES HERE --><!-- ADD NOTES HERE -->
        <!-- ADD NOTES HERE --><!-- ADD NOTES HERE -->
        <dl>
          <dt class="keyTerms pointer">Example Collapse <span class="normal blue pointer" id="show_n01"
              onclick="swap_text('show_n01','notes_01') ">[toggle...]</span>
          </dt>
          <dd id="notes_01" class="displaynone"> <!-- hidden then revealed -->
            <p>Something you want to be collapsed at first:
              <code>some code maybe</code> or</p>
            <pre>maybe some
&#x3c;preformatted&#x3e;
text here.</pre>
          </dd>

          <dt class="keyTerms pointer">Peek-a-boo Code:<span class="normal blue pointer" id="show_n02"
              onclick="swap_text('show_n02','notes_02') ">[toggle...]</span>
          </dt>
          <dd id="notes_02" class="displaynone"> <!-- hidden then revealed -->
            <pre>
function register_custom_post_type() {
    register_post_type('form_log', array(
        'labels' => array(
            'name' => __('Form Logs'),
            'singular_name' => __('Form Log')
        ),
        'public' => true,
        'has_archive' => true,
        'supports' => array('title', 'editor'),
    ));
}
add_action('init', 'register_custom_post_type');</pre>
          </dd>
        </dl>

        <!-- END NOTES --><!-- END NOTES -->
        <!-- END NOTES --><!-- END NOTES -->


      </div> <!-- $ end .notes div -->
    </section>
    <section> <!-- :begin #_GLOSSARY  -->
      <div>
        <h2>Glossary:</h2>
        <h3>Key Terms about <?php print $page_heading; ?></h3>
        <dl>
        <dt class="pointer">Show Glossary<span class="normal blue pointer" id="show_g01"
              onclick="swap_text('show_g01','glossary_01') ">[toggle...]</span>
          </dt>
          <dd id="glossary_01" class="displaynone">
            <p>Maybe this is a note about a framework&apos;s folder structure...</p>
            <pre>#       /var/www/html/framework_name/
#       |-- some.file.name
#       |-- some.ts
#       |-- some.json
#       |-- some.js</pre>
<p>Remember: There are tools, such as the Linux command line tool, <code>tree</code> which can generate the
                tree in various formats including <strong>JSON and HTML</strong>. E.g. <code>tree -J</code> or <code>tree -H http://path/of/dir</code></p>
            <p><kbd>apt install tree</kbd></p>
          </dd>
        </dl>
      </div> <!-- $ :end #_glossary -->
    </section>
    <footer class="footer px-4"> <!--    .FOOTER     -->
      <div class="row gx-5">
        <div class="col">
          <div class="p-3 border bg-light"> Based on Notes by <a href="https://github.com/ajaxStardust" target="_blank"
              title="View original">@ajaxStardust</a> <em>Laravel</em> notes:</div>
        </div>
        <div class="col">
          <div class="p-3 border bg-light text-end"><kbd>
              <?php echo $lastMod; ?>
            </kbd></div>
        </div>
      </div>
    </footer>
  </div><!--    $ :end    END class.content (former id.maincol)    $    -->

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
    crossorigin="anonymous"></script>
  <script src="assets/js/showme-hideme.js"></script>

</body>

</html>
