<?php
/**
 * Adb_simplest/template.phtml
 *
 * Copyright 2023 @ajaxStardust <flux@mx23>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301, USA.
 *
 * @category  Content_Management
 * @package   Anniedebrowsa
 * @author    Display Name <flux@devel.com>
 * @copyright 2023 @ajaxStardust
 * @license   http://www.gnu.org/licenses/gpl-2.0.html
 * @link      https://github.com/ajaxStardust/anniedebrowsa
 * @version   1.0
 * @since     1.0
 **/

header('Access-Control-Allow-Origin: *'); // ENABLE CORS (Cross-Origin Request) policy allow all - CAUTION: not-ready-for-prime-time player
date_default_timezone_set('EST');
$page_heading = '&#x201c;Simple Template&#x201d; ';
$title = 'Basic TEMPLATE';
$lastMod = "Modified: " . date("D M j Y G:i:s T", getlastmod());
?>
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>
    <?php print $title; ?>
  </title>
  <link rel="icon" type="image/ico" href="favicon.ico">
  <link rel="shortcut icon" type="image/ico" href="favicon.ico">

  <style>
    .tsw {
      font-family: "source serif pro";
      font-size: 1.2rem;
      font-style: italic;
    }

    /** if needed add style here
                                ** NOTE THE NEW favICON code here:
                                **
                                */
  </style>
  <link rel="icon" href="./favicon.ico" sizes="32x32">
  <link rel="icon" href="./favicon.ico" sizes="192x192">
  <link rel="apple-touch-icon" href="./favicon.ico">
  <meta name="msapplication-TileImage" content="<!-- http://.file./ -->">


  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
  <!-- BOOTSTRAP STYLE -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
  <link href="https://api.mapbox.com/mapbox-gl-js/v2.1.1/mapbox-gl.css" rel="stylesheet">
  <link href="assets/css/notes.css" rel="stylesheet" type="text/css">
  <script>
  /*
 *
 * Copyright (c) 2006/2007 Sam Collett (http://www.texotela.co.uk)
 * Licensed under the MIT License:
 * http://www.opensource.org/licenses/mit-license.php
 * 
 * Version 2.0
 * Demo: http://www.texotela.co.uk/code/jquery/newsticker/
 *
 * $LastChangedDate: 2007-05-29 11:31:36 +0100 (Tue, 29 May 2007) $
 * $Rev: 2005 $
 *
 */
 
(function($) {
/*
 * A basic news ticker.
 *
 * @name     newsticker (or newsTicker)
 * @param    delay      Delay (in milliseconds) between iterations. Default 4 seconds (4000ms)
 * @author   Sam Collett (http://www.texotela.co.uk)
 * @example  $("#news").newsticker(); // or $("#news").newsTicker(5000);
 *
 */
$.fn.newsTicker = $.fn.newsticker = function(delay)
{
	delay = delay || 4000;
	initTicker = function(el)
	{
		stopTicker(el);
		el.items = $("li", el);
		// hide all items (except first one)
		el.items.not(":eq(0)").hide().end();
		// current item
		el.currentitem = 0;
		startTicker(el);
	};
	startTicker = function(el)
	{
		el.tickfn = setInterval(function() { doTick(el) }, delay)
	};
	stopTicker = function(el)
	{
		clearInterval(el.tickfn);
	};
	pauseTicker = function(el)
	{
		el.pause = true;
	};
	resumeTicker = function(el)
	{
		el.pause = false;
	};
	doTick = function(el)
	{
		// don't run if paused
		if(el.pause) return;
		// pause until animation has finished
		el.pause = true;
		// hide current item
		$(el.items[el.currentitem]).fadeOut("slow",
			function()
			{
				$(this).hide();
				// move to next item and show
				el.currentitem = ++el.currentitem % (el.items.size());
				$(el.items[el.currentitem]).fadeIn("slow",
					function()
					{
						el.pause = false;
					}
				);
			}
		);
	};
	this.each(
		function()
		{
			if(this.nodeName.toLowerCase()!= "ul") return;
			initTicker(this);
		}
	)
	.addClass("newsticker")
	.hover(
		function()
		{
			// pause if hovered over
			pauseTicker(this);
		},
		function()
		{
			// resume when not hovered over
			resumeTicker(this);
		}
	);
	return this;
};

})(jQuery);
</script>
</head>

<body>

  <div id="pagewidth" class="container"> <!--    :begin    class:content        -->

    <section id="header"> <!-- #HEADER -->
      <h1 class="bg-dark text-light text-end pe-3">
        <?php print $page_heading; ?>
      </h1>
    </section>
    <section id="general_notes">
      <h2>General Notes</h2>
      <div class="notes">
<p>lets play with jQuery:</p>
<script>
  $("#news").newsTicker(5000);
</script>
        <dl>
          <dt class="keyTerms pointer">Example Collapse <span class="normal blue pointer" id="show_n01"
              onclick="swap_text('show_n01','notes_01') ">[toggle...]</span>
          </dt>
          <dd id="notes_01" class="displaynone"> <!-- hidden then revealed -->
            <p>Something you want to be collapsed at first:
              <code>some code maybe</code> or</p>
            <pre>maybe some
&#x3c;preformatted&#x3e; 
text here.</pre>
          </dd>

          <dt class="keyTerms pointer">Reveal random: <span class="normal blue pointer" id="show_n02"
              onclick="swap_text('show_n02','notes_02') ">[toggle...]</span>
          </dt>
          <dd id="notes_02" class="displaynone"> <!-- hidden then revealed -->
            <p>Some Random content
          </dd>
        </dl>

        <!-- END NOTES --><!-- END NOTES -->
        <!-- END NOTES --><!-- END NOTES -->


      </div> <!-- $ end .notes div -->
    </section>
    <section> <!-- :begin #_GLOSSARY  -->
      <div>
        <h2>Glossary:</h2>
        <h3>Key Terms about <?php print $page_heading; ?></h3>
        <dl>
        <dt class="pointer">Show Glossary<span class="normal blue pointer" id="show_g01"
              onclick="swap_text('show_g01','glossary_01') ">[toggle...]</span>
          </dt>
          <dd id="glossary_01" class="displaynone">
            <p>Maybe this is a note about a framework&apos;s folder structure...</p>
            <pre>#       /var/www/html/framework_name/
#       |-- some.file.name
#       |-- some.ts
#       |-- some.json
#       |-- some.js</pre>
<p>Remember: There are tools, such as the Linux command line tool, <code>tree</code> which can generate the
                tree in various formats including <strong>JSON and HTML</strong>. E.g. <code>tree -J</code> or <code>tree -H http://path/of/dir</code></p>
            <p><kbd>apt install tree</kbd></p>
          </dd>
        </dl>
      </div> <!-- $ :end #_glossary -->
    </section>
    <footer class="footer px-4"> <!--    .FOOTER     -->
      <div class="row gx-5">
        <div class="col">
          <div class="p-3 border bg-light"> Based on Notes by <a href="https://github.com/ajaxStardust" target="_blank"
              title="View original">@ajaxStardust</a> <em>Laravel</em> notes:</div>
        </div>
        <div class="col">
          <div class="p-3 border bg-light text-end"><kbd>
              <?php echo $lastMod; ?>
            </kbd></div>
        </div>
      </div>
    </footer>
  </div><!--    $ :end    END class.content (former id.maincol)    $    -->
 
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
    crossorigin="anonymous"></script>
  <script src="assets/js/showme-hideme.js"></script>

</body>

</html>
