<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en" >
<head>
	<meta charset="UTF-8">
	<meta http-equiv="Content-Style-Type" content="text/css" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Coverage of Misc Symbols by DejaVu Sans Condensed</title>
 
	<link href="assets/css/notes.css" rel="stylesheet" type="text/css" media="screen" />
<style type="text/css">

body, html, .content {
	background-color: #0A0A00;
	color:#FFFFFA;
}

div.content ol li {
  font-family:"dejavu sans condensed","dejavu sans","arial unicode",sans-serif;
  font-size:medium;
}

/*
li:first-letter {
  color:#F00;
}
*/

ol li, ul li {
	list-style-type:none;
	width:60%;
}

.blueshadow {
	/*background-color: #DDE4E9;*/
	/*border-bottom-color: #E8EDF0;*/
	/*border-bottom-style: solid;*/
	/*border-bottom-width: 5px;*/
	/*border-left-color-value: #E8EDF0;*/
	/*border-left-style-value: solid;*/
	/*border-left-width-value: 5px;*/
	/*border-right-color-value: #E8EDF0;*/
	/*border-right-style-value: solid;*/
	/*border-right-width-value: 5px;*/
	/*border-top-color: #E8EDF0;*/
	/*border-top-style: solid;*/
	/*border-top-width: 5px;*/
	/*box-shadow: 0 2px 3px #D1DAE1 inset;*/
	/*padding-bottom: 5px;*/
	/*padding-left: 15px;*/
	/*padding-right: 15px;*/
	/*padding-top: 15px;*/
	text-shadow: 0.03em 0.06em 0.08em rgba(50, 50, 50, 0.6);
	/*width:inherit;*/
	color:#0C0EEF;
	position:absolute;
	float:left;
	left:56%;
	font-size: 3em;
	background-color: #FAFAFA;
	color:#0A0A00;
	padding:0 0.3em;
	/* display: block; */
	
}

.blueshadow::before {
	content:"."
	padding-left:2em;
	margin-left:2em;
}

.red {
	/*background-color: #DDE4E9;*/
	/*border: 5px solid #E8EDF0;*/
	/*box-shadow: 0 2px 3px #D1DAE1 inset;*/
	/*padding: 15px 15px 5px;*/
	/*text-shadow: 0 1px 0 #FFFFFF;*/
	/*color:#c30000;*/
}
.font_support {
	font-variant: small-caps;
	color: rgba(128,128,128,0.8);
	font-size-adjust: 0.33;
	vertical-align: super;
}
#install a {
	background-color: black;
}
#install a:hover {
	background-color: #0A0A0F;
}
ol.unilist li {
	margin: 1em 0;
/* 	outline-color: #000;
	outline-width: 0.1%;
	outline-style: auto; */
	border: 3px solid #0F0F10;
	padding: 0.5em;
	width: 90%;
	
}

.content a {
	background-color: black;
}
#introitem {
	background-color: #121212;
	font-weight: 800;
	
}
#introitem .blueshadow {
	font-size: 1.5em;
	
}
h1 {
	padding-left: 0.8em;
}
</style>
</head>
<body>
<div class="content">
<h1>Coverage of Miscellaneous Symbols by DejaVu Sans Condensed</h1>
<p id="install">To view the unicode symbols, <a href="https://www.fontsquirrel.com/fonts/dejavu-sans" title="instasll Dejavu Sans" alt="install DejaVu Sans" target="_BLANK">download</a> and install the DejaVu Sans font .TTF </p>

<ol class="unilist">
<li id="introitem"><span class="blueshadow">glyph</span><br />
	<span class="red">Unicode NCR</span>	COMMON NAME	<span class="font_support">(Font: Support Status)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2600;</span><br />
	<span class="red">&#x26;#x2600;</span>	BLACK SUN WITH RAYS	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2601;</span><br />
	<span class="red">&#x26;#x2601;</span>	CLOUD	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2602;</span><br />
	<span class="red">&#x26;#x2602;</span>	UMBRELLA	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2603;</span><br />
	<span class="red">&#x26;#x2603;</span>	SNOWMAN	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2604;</span><br />
	<span class="red">&#x26;#x2604;</span>	COMET	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2605;</span><br />
	<span class="red">&#x26;#x2605;</span>	BLACK STAR	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2606;</span><br />
	<span class="red">&#x26;#x2606;</span>	WHITE STAR	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2607;</span><br />
	<span class="red">&#x26;#x2607;</span>	LIGHTNING	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2608;</span><br />
	<span class="red">&#x26;#x2608;</span>	THUNDERSTORM	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2609;</span><br />
	<span class="red">&#x26;#x2609;</span>	SUN	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x260A;</span><br />
	<span class="red">&#x26;#x260A;</span>	ASCENDING NODE	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x260B;</span><br />
	<span class="red">&#x26;#x260B;</span>	DESCENDING NODE	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x260C;</span><br />
	<span class="red">&#x26;#x260C;</span>	CONJUNCTION	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x260D;</span><br />
	<span class="red">&#x26;#x260D;</span>	OPPOSITION	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x260E;</span><br />
	<span class="red">&#x26;#x260E;</span>	BLACK TELEPHONE	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x260F;</span><br />
	<span class="red">&#x26;#x260F;</span>	WHITE TELEPHONE	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2610;</span><br />
	<span class="red">&#x26;#x2610;</span>	BALLOT BOX	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2611;</span><br />
	<span class="red">&#x26;#x2611;</span>	BALLOT BOX WITH CHECK	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2612;</span><br />
	<span class="red">&#x26;#x2612;</span>	BALLOT BOX WITH X	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2613;</span><br />
	<span class="red">&#x26;#x2613;</span>	SALTIRE	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2614;</span><br />
	<span class="red">&#x26;#x2614;</span>	UMBRELLA WITH RAIN DROPS	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2615;</span><br />
	<span class="red">&#x26;#x2615;</span>	HOT BEVERAGE	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2616;</span><br />
	<span class="red">&#x26;#x2616;</span>	WHITE SHOGI PIECE	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2617;</span><br />
	<span class="red">&#x26;#x2617;</span>	BLACK SHOGI PIECE	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2618;</span><br />
	<span class="red">&#x26;#x2618;</span>	SHAMROCK	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2619;</span><br />
	<span class="red">&#x26;#x2619;</span>	REVERSED ROTATED FLORAL HEART BULLET	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x261A;</span><br />
	<span class="red">&#x26;#x261A;</span>	BLACK LEFT POINTING INDEX	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x261B;</span><br />
	<span class="red">&#x26;#x261B;</span>	BLACK RIGHT POINTING INDEX	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x261C;</span><br />
	<span class="red">&#x26;#x261C;</span>	WHITE LEFT POINTING INDEX	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x261D;</span><br />
	<span class="red">&#x26;#x261D;</span>	WHITE UP POINTING INDEX	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x261E;</span><br />
	<span class="red">&#x26;#x261E;</span>	WHITE RIGHT POINTING INDEX	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x261F;</span><br />
	<span class="red">&#x26;#x261F;</span>	WHITE DOWN POINTING INDEX	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2620;</span><br />
	<span class="red">&#x26;#x2620;</span>	SKULL AND CROSSBONES	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2621;</span><br />
	<span class="red">&#x26;#x2621;</span>	CAUTION SIGN	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2622;</span><br />
	<span class="red">&#x26;#x2622;</span>	RADIOACTIVE SIGN	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2623;</span><br />
	<span class="red">&#x26;#x2623;</span>	BIOHAZARD SIGN	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2624;</span><br />
	<span class="red">&#x26;#x2624;</span>	CADUCEUS	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2625;</span><br />
	<span class="red">&#x26;#x2625;</span>	ANKH	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2626;</span><br />
	<span class="red">&#x26;#x2626;</span>	ORTHODOX CROSS	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2627;</span><br />
	<span class="red">&#x26;#x2627;</span>	CHI RHO	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2628;</span><br />
	<span class="red">&#x26;#x2628;</span>	CROSS OF LORRAINE	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2629;</span><br />
	<span class="red">&#x26;#x2629;</span>	CROSS OF JERUSALEM	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x262A;</span><br />
	<span class="red">&#x26;#x262A;</span>	STAR AND CRESCENT	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x262B;</span><br />
	<span class="red">&#x26;#x262B;</span>	FARSI SYMBOL	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x262C;</span><br />
	<span class="red">&#x26;#x262C;</span>	ADI SHAKTI	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x262D;</span><br />
	<span class="red">&#x26;#x262D;</span>	HAMMER AND SICKLE	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x262E;</span><br />
	<span class="red">&#x26;#x262E;</span>	PEACE SYMBOL	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x262F;</span><br />
	<span class="red">&#x26;#x262F;</span>	YIN YANG	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2630;</span><br />
	<span class="red">&#x26;#x2630;</span>	TRIGRAM FOR HEAVEN	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2631;</span><br />
	<span class="red">&#x26;#x2631;</span>	TRIGRAM FOR LAKE	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2632;</span><br />
	<span class="red">&#x26;#x2632;</span>	TRIGRAM FOR FIRE	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2633;</span><br />
	<span class="red">&#x26;#x2633;</span>	TRIGRAM FOR THUNDER	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2634;</span><br />
	<span class="red">&#x26;#x2634;</span>	TRIGRAM FOR WIND	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2635;</span><br />
	<span class="red">&#x26;#x2635;</span>	TRIGRAM FOR WATER	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2636;</span><br />
	<span class="red">&#x26;#x2636;</span>	TRIGRAM FOR MOUNTAIN	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2637;</span><br />
	<span class="red">&#x26;#x2637;</span>	TRIGRAM FOR EARTH	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2638;</span><br />
	<span class="red">&#x26;#x2638;</span>	WHEEL OF DHARMA	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2639;</span><br />
	<span class="red">&#x26;#x2639;</span>	WHITE FROWNING FACE	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x263A;</span><br />
	<span class="red">&#x26;#x263A;</span>	WHITE SMILING FACE	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x263B;</span><br />
	<span class="red">&#x26;#x263B;</span>	BLACK SMILING FACE	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x263C;</span><br />
	<span class="red">&#x26;#x263C;</span>	WHITE SUN WITH RAYS	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x263D;</span><br />
	<span class="red">&#x26;#x263D;</span>	FIRST QUARTER MOON	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x263E;</span><br />
	<span class="red">&#x26;#x263E;</span>	LAST QUARTER MOON	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x263F;</span><br />
	<span class="red">&#x26;#x263F;</span>	MERCURY	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2640;</span><br />
	<span class="red">&#x26;#x2640;</span>	FEMALE SIGN	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2641;</span><br />
	<span class="red">&#x26;#x2641;</span>	EARTH	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2642;</span><br />
	<span class="red">&#x26;#x2642;</span>	MALE SIGN	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2643;</span><br />
	<span class="red">&#x26;#x2643;</span>	JUPITER	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2644;</span><br />
	<span class="red">&#x26;#x2644;</span>	SATURN	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2645;</span><br />
	<span class="red">&#x26;#x2645;</span>	URANUS	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2646;</span><br />
	<span class="red">&#x26;#x2646;</span>	NEPTUNE	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2647;</span><br />
	<span class="red">&#x26;#x2647;</span>	PLUTO	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2648;</span><br />
	<span class="red">&#x26;#x2648;</span>	ARIES	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2649;</span><br />
	<span class="red">&#x26;#x2649;</span>	TAURUS	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x264A;</span><br />
	<span class="red">&#x26;#x264A;</span>	GEMINI	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x264B;</span><br />
	<span class="red">&#x26;#x264B;</span>	CANCER	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x264C;</span><br />
	<span class="red">&#x26;#x264C;</span>	LEO	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x264D;</span><br />
	<span class="red">&#x26;#x264D;</span>	VIRGO	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x264E;</span><br />
	<span class="red">&#x26;#x264E;</span>	LIBRA	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x264F;</span><br />
	<span class="red">&#x26;#x264F;</span>	SCORPIUS	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2650;</span><br />
	<span class="red">&#x26;#x2650;</span>	SAGITTARIUS	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2651;</span><br />
	<span class="red">&#x26;#x2651;</span>	CAPRICORN	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2652;</span><br />
	<span class="red">&#x26;#x2652;</span>	AQUARIUS	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2653;</span><br />
	<span class="red">&#x26;#x2653;</span>	PISCES	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2654;</span><br />
	<span class="red">&#x26;#x2654;</span>	WHITE CHESS KING	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2655;</span><br />
	<span class="red">&#x26;#x2655;</span>	WHITE CHESS QUEEN	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2656;</span><br />
	<span class="red">&#x26;#x2656;</span>	WHITE CHESS ROOK	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2657;</span><br />
	<span class="red">&#x26;#x2657;</span>	WHITE CHESS BISHOP	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2658;</span><br />
	<span class="red">&#x26;#x2658;</span>	WHITE CHESS KNIGHT	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2659;</span><br />
	<span class="red">&#x26;#x2659;</span>	WHITE CHESS PAWN	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x265A;</span><br />
	<span class="red">&#x26;#x265A;</span>	BLACK CHESS KING	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x265B;</span><br />
	<span class="red">&#x26;#x265B;</span>	BLACK CHESS QUEEN	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x265C;</span><br />
	<span class="red">&#x26;#x265C;</span>	BLACK CHESS ROOK	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x265D;</span><br />
	<span class="red">&#x26;#x265D;</span>	BLACK CHESS BISHOP	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x265E;</span><br />
	<span class="red">&#x26;#x265E;</span>	BLACK CHESS KNIGHT	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x265F;</span><br />
	<span class="red">&#x26;#x265F;</span>	BLACK CHESS PAWN	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2660;</span><br />
	<span class="red">&#x26;#x2660;</span>	BLACK SPADE SUIT	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2661;</span><br />
	<span class="red">&#x26;#x2661;</span>	WHITE HEART SUIT	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2662;</span><br />
	<span class="red">&#x26;#x2662;</span>	WHITE DIAMOND SUIT	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2663;</span><br />
	<span class="red">&#x26;#x2663;</span>	BLACK CLUB SUIT	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2664;</span><br />
	<span class="red">&#x26;#x2664;</span>	WHITE SPADE SUIT	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2665;</span><br />
	<span class="red">&#x26;#x2665;</span>	BLACK HEART SUIT	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2666;</span><br />
	<span class="red">&#x26;#x2666;</span>	BLACK DIAMOND SUIT	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2667;</span><br />
	<span class="red">&#x26;#x2667;</span>	WHITE CLUB SUIT	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2668;</span><br />
	<span class="red">&#x26;#x2668;</span>	HOT SPRINGS	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2669;</span><br />
	<span class="red">&#x26;#x2669;</span>	QUARTER NOTE	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x266A;</span><br />
	<span class="red">&#x26;#x266A;</span>	EIGHTH NOTE	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x266B;</span><br />
	<span class="red">&#x26;#x266B;</span>	BEAMED EIGHTH NOTES	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x266C;</span><br />
	<span class="red">&#x26;#x266C;</span>	BEAMED SIXTEENTH NOTES	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x266D;</span><br />
	<span class="red">&#x26;#x266D;</span>	MUSIC FLAT SIGN	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x266E;</span><br />
	<span class="red">&#x26;#x266E;</span>	MUSIC NATURAL SIGN	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x266F;</span><br />
	<span class="red">&#x26;#x266F;</span>	MUSIC SHARP SIGN	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2670;</span><br />
	<span class="red">&#x26;#x2670;</span>	WEST SYRIAC CROSS	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2671;</span><br />
	<span class="red">&#x26;#x2671;</span>	EAST SYRIAC CROSS	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2672;</span><br />
	<span class="red">&#x26;#x2672;</span>	UNIVERSAL RECYCLING SYMBOL	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2673;</span><br />
	<span class="red">&#x26;#x2673;</span>	RECYCLING SYMBOL FOR TYPE-1 PLASTICS	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2674;</span><br />
	<span class="red">&#x26;#x2674;</span>	RECYCLING SYMBOL FOR TYPE-2 PLASTICS	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2675;</span><br />
	<span class="red">&#x26;#x2675;</span>	RECYCLING SYMBOL FOR TYPE-3 PLASTICS	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2676;</span><br />
	<span class="red">&#x26;#x2676;</span>	RECYCLING SYMBOL FOR TYPE-4 PLASTICS	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2677;</span><br />
	<span class="red">&#x26;#x2677;</span>	RECYCLING SYMBOL FOR TYPE-5 PLASTICS	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2678;</span><br />
	<span class="red">&#x26;#x2678;</span>	RECYCLING SYMBOL FOR TYPE-6 PLASTICS	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2679;</span><br />
	<span class="red">&#x26;#x2679;</span>	RECYCLING SYMBOL FOR TYPE-7 PLASTICS	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x267A;</span><br />
	<span class="red">&#x26;#x267A;</span>	RECYCLING SYMBOL FOR GENERIC MATERIALS	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x267B;</span><br />
	<span class="red">&#x26;#x267B;</span>	BLACK UNIVERSAL RECYCLING SYMBOL	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x267C;</span><br />
	<span class="red">&#x26;#x267C;</span>	RECYCLED PAPER SYMBOL	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x267D;</span><br />
	<span class="red">&#x26;#x267D;</span>	PARTIALLY-RECYCLED PAPER SYMBOL	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x267E;</span><br />
	<span class="red">&#x26;#x267E;</span>	PERMANENT PAPER SIGN	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x267F;</span><br />
	<span class="red">&#x26;#x267F;</span>	WHEELCHAIR SYMBOL	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2680;</span><br />
	<span class="red">&#x26;#x2680;</span>	DIE FACE-1	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2681;</span><br />
	<span class="red">&#x26;#x2681;</span>	DIE FACE-2	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2682;</span><br />
	<span class="red">&#x26;#x2682;</span>	DIE FACE-3	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2683;</span><br />
	<span class="red">&#x26;#x2683;</span>	DIE FACE-4	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2684;</span><br />
	<span class="red">&#x26;#x2684;</span>	DIE FACE-5	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2685;</span><br />
	<span class="red">&#x26;#x2685;</span>	DIE FACE-6	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2686;</span><br />
	<span class="red">&#x26;#x2686;</span>	WHITE CIRCLE WITH DOT RIGHT	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2687;</span><br />
	<span class="red">&#x26;#x2687;</span>	WHITE CIRCLE WITH TWO DOTS	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2688;</span><br />
	<span class="red">&#x26;#x2688;</span>	BLACK CIRCLE WITH WHITE DOT RIGHT	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2689;</span><br />
	<span class="red">&#x26;#x2689;</span>	BLACK CIRCLE WITH TWO WHITE DOTS	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x268A;</span><br />
	<span class="red">&#x26;#x268A;</span>	MONOGRAM FOR YANG	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x268B;</span><br />
	<span class="red">&#x26;#x268B;</span>	MONOGRAM FOR YIN	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x268C;</span><br />
	<span class="red">&#x26;#x268C;</span>	DIGRAM FOR GREATER YANG	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x268D;</span><br />
	<span class="red">&#x26;#x268D;</span>	DIGRAM FOR LESSER YIN	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x268E;</span><br />
	<span class="red">&#x26;#x268E;</span>	DIGRAM FOR LESSER YANG	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x268F;</span><br />
	<span class="red">&#x26;#x268F;</span>	DIGRAM FOR GREATER YIN	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2690;</span><br />
	<span class="red">&#x26;#x2690;</span>	WHITE FLAG	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2691;</span><br />
	<span class="red">&#x26;#x2691;</span>	BLACK FLAG	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2692;</span><br />
	<span class="red">&#x26;#x2692;</span>	HAMMER AND PICK	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2693;</span><br />
	<span class="red">&#x26;#x2693;</span>	ANCHOR	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2694;</span><br />
	<span class="red">&#x26;#x2694;</span>	CROSSED SWORDS	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2695;</span><br />
	<span class="red">&#x26;#x2695;</span>	STAFF OF AESCULAPIUS	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2696;</span><br />
	<span class="red">&#x26;#x2696;</span>	SCALES	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2697;</span><br />
	<span class="red">&#x26;#x2697;</span>	ALEMBIC	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2698;</span><br />
	<span class="red">&#x26;#x2698;</span>	FLOWER	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x2699;</span><br />
	<span class="red">&#x26;#x2699;</span>	GEAR	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x269A;</span><br />
	<span class="red">&#x26;#x269A;</span>	STAFF OF HERMES	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x269B;</span><br />
	<span class="red">&#x26;#x269B;</span>	ATOM SYMBOL	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x269C;</span><br />
	<span class="red">&#x26;#x269C;</span>	FLEUR-DE-LIS	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x269D;</span><br />
	<span class="red">&#x26;#x269D;</span>	OUTLINED WHITE STAR	<span class="font_support">(DejaVu: Not Yet)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x269E;</span><br />
	<span class="red">&#x26;#x269E;</span>	THREE LINES CONVERGING RIGHT	<span class="font_support">(DejaVu: Not Yet)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x269F;</span><br />
	<span class="red">&#x26;#x269F;</span>	THREE LINES CONVERGING LEFT	<span class="font_support">(DejaVu: Not Yet)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26A0;</span><br />
	<span class="red">&#x26;#x26A0;</span>	WARNING SIGN	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26A1;</span><br />
	<span class="red">&#x26;#x26A1;</span>	HIGH VOLTAGE SIGN	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26A2;</span><br />
	<span class="red">&#x26;#x26A2;</span>	DOUBLED FEMALE SIGN	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26A3;</span><br />
	<span class="red">&#x26;#x26A3;</span>	DOUBLED MALE SIGN	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26A4;</span><br />
	<span class="red">&#x26;#x26A4;</span>	INTERLOCKED FEMALE AND MALE SIGN	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26A5;</span><br />
	<span class="red">&#x26;#x26A5;</span>	MALE AND FEMALE SIGN	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26A6;</span><br />
	<span class="red">&#x26;#x26A6;</span>	MALE WITH STROKE SIGN	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26A7;</span><br />
	<span class="red">&#x26;#x26A7;</span>	MALE WITH STROKE AND MALE AND FEMALE SIGN	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26A8;</span><br />
	<span class="red">&#x26;#x26A8;</span>	VERTICAL MALE WITH STROKE SIGN	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26A9;</span><br />
	<span class="red">&#x26;#x26A9;</span>	HORIZONTAL MALE WITH STROKE SIGN	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26AA;</span><br />
	<span class="red">&#x26;#x26AA;</span>	MEDIUM WHITE CIRCLE	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26AB;</span><br />
	<span class="red">&#x26;#x26AB;</span>	MEDIUM BLACK CIRCLE	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26AC;</span><br />
	<span class="red">&#x26;#x26AC;</span>	MEDIUM SMALL WHITE CIRCLE	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26AD;</span><br />
	<span class="red">&#x26;#x26AD;</span>	MARRIAGE SYMBOL	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26AE;</span><br />
	<span class="red">&#x26;#x26AE;</span>	DIVORCE SYMBOL	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26AF;</span><br />
	<span class="red">&#x26;#x26AF;</span>	UNMARRIED PARTNERSHIP SYMBOL	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26B0;</span><br />
	<span class="red">&#x26;#x26B0;</span>	COFFIN	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26B1;</span><br />
	<span class="red">&#x26;#x26B1;</span>	FUNERAL URN	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26B2;</span><br />
	<span class="red">&#x26;#x26B2;</span>	NEUTER	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26B3;</span><br />
	<span class="red">&#x26;#x26B3;</span>	CERES	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26B4;</span><br />
	<span class="red">&#x26;#x26B4;</span>	PALLAS	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26B5;</span><br />
	<span class="red">&#x26;#x26B5;</span>	JUNO	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26B6;</span><br />
	<span class="red">&#x26;#x26B6;</span>	VESTA	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26B7;</span><br />
	<span class="red">&#x26;#x26B7;</span>	CHIRON	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26B8;</span><br />
	<span class="red">&#x26;#x26B8;</span>	BLACK MOON LILITH	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26B9;</span><br />
	<span class="red">&#x26;#x26B9;</span>	SEXTILE	<span class="font_support">(DejaVu: Not Yet)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26BA;</span><br />
	<span class="red">&#x26;#x26BA;</span>	SEMISEXTILE	<span class="font_support">(DejaVu: Not Yet)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26BB;</span><br />
	<span class="red">&#x26;#x26BB;</span>	QUINCUNX	<span class="font_support">(DejaVu: Not Yet)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26BC;</span><br />
	<span class="red">&#x26;#x26BC;</span>	SESQUIQUADRATE	<span class="font_support">(DejaVu: Not Yet)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26BD;</span><br />
	<span class="red">&#x26;#x26BD;</span>	SOCCER BALL	<span class="font_support">(DejaVu: Not Yet)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26BE;</span><br />
	<span class="red">&#x26;#x26BE;</span>	BASEBALL	<span class="font_support">(DejaVu: Not Yet)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26BF;</span><br />
	<span class="red">&#x26;#x26BF;</span>	SQUARED KEY	<span class="font_support">(DejaVu: Not Yet)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26C0;</span><br />
	<span class="red">&#x26;#x26C0;</span>	WHITE DRAUGHTS MAN	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26C1;</span><br />
	<span class="red">&#x26;#x26C1;</span>	WHITE DRAUGHTS KING	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26C2;</span><br />
	<span class="red">&#x26;#x26C2;</span>	BLACK DRAUGHTS MAN	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26C3;</span><br />
	<span class="red">&#x26;#x26C3;</span>	BLACK DRAUGHTS KING	<span class="font_support">(DejaVu: Supported)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26C4;</span><br />
	<span class="red">&#x26;#x26C4;</span>	SNOWMAN WITHOUT SNOW	<span class="font_support">(DejaVu: Not Yet)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26C5;</span><br />
	<span class="red">&#x26;#x26C5;</span>	SUN BEHIND CLOUD	<span class="font_support">(DejaVu: Not Yet)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26C6;</span><br />
	<span class="red">&#x26;#x26C6;</span>	RAIN	<span class="font_support">(DejaVu: Not Yet)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26C7;</span><br />
	<span class="red">&#x26;#x26C7;</span>	BLACK SNOWMAN	<span class="font_support">(DejaVu: Not Yet)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26C8;</span><br />
	<span class="red">&#x26;#x26C8;</span>	THUNDER CLOUD AND RAIN	<span class="font_support">(DejaVu: Not Yet)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26C9;</span><br />
	<span class="red">&#x26;#x26C9;</span>	TURNED WHITE SHOGI PIECE	<span class="font_support">(DejaVu: Not Yet)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26CA;</span><br />
	<span class="red">&#x26;#x26CA;</span>	TURNED BLACK SHOGI PIECE	<span class="font_support">(DejaVu: Not Yet)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26CB;</span><br />
	<span class="red">&#x26;#x26CB;</span>	WHITE DIAMOND IN SQUARE	<span class="font_support">(DejaVu: Not Yet)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26CC;</span><br />
	<span class="red">&#x26;#x26CC;</span>	CROSSING LANES	<span class="font_support">(DejaVu: Not Yet)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26CD;</span><br />
	<span class="red">&#x26;#x26CD;</span>	DISABLED CAR	<span class="font_support">(DejaVu: Not Yet)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26CE;</span><br />
	<span class="red">&#x26;#x26CE;</span>	OPHIUCHUS	<span class="font_support">(DejaVu: Not Yet)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26CF;</span><br />
	<span class="red">&#x26;#x26CF;</span>	PICK	<span class="font_support">(DejaVu: Not Yet)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26D0;</span><br />
	<span class="red">&#x26;#x26D0;</span>	CAR SLIDING	<span class="font_support">(DejaVu: Not Yet)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26D1;</span><br />
	<span class="red">&#x26;#x26D1;</span>	HELMET WITH WHITE CROSS	<span class="font_support">(DejaVu: Not Yet)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26D2;</span><br />
	<span class="red">&#x26;#x26D2;</span>	CIRCLED CROSSING LANES	<span class="font_support">(DejaVu: Not Yet)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26D3;</span><br />
	<span class="red">&#x26;#x26D3;</span>	CHAINS	<span class="font_support">(DejaVu: Not Yet)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26D4;</span><br />
	<span class="red">&#x26;#x26D4;</span>	NO ENTRY	<span class="font_support">(DejaVu: Not Yet)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26D5;</span><br />
	<span class="red">&#x26;#x26D5;</span>	ALTERNATE ONE-WAY LEFT WAY TRAFFIC	<span class="font_support">(DejaVu: Not Yet)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26D6;</span><br />
	<span class="red">&#x26;#x26D6;</span>	BLACK TWO-WAY LEFT WAY TRAFFIC	<span class="font_support">(DejaVu: Not Yet)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26D7;</span><br />
	<span class="red">&#x26;#x26D7;</span>	WHITE TWO-WAY LEFT WAY TRAFFIC	<span class="font_support">(DejaVu: Not Yet)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26D8;</span><br />
	<span class="red">&#x26;#x26D8;</span>	BLACK LEFT LANE MERGE	<span class="font_support">(DejaVu: Not Yet)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26D9;</span><br />
	<span class="red">&#x26;#x26D9;</span>	WHITE LEFT LANE MERGE	<span class="font_support">(DejaVu: Not Yet)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26DA;</span><br />
	<span class="red">&#x26;#x26DA;</span>	DRIVE SLOW SIGN	<span class="font_support">(DejaVu: Not Yet)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26DB;</span><br />
	<span class="red">&#x26;#x26DB;</span>	HEAVY WHITE DOWN-POINTING TRIANGLE	<span class="font_support">(DejaVu: Not Yet)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26DC;</span><br />
	<span class="red">&#x26;#x26DC;</span>	LEFT CLOSED ENTRY	<span class="font_support">(DejaVu: Not Yet)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26DD;</span><br />
	<span class="red">&#x26;#x26DD;</span>	SQUARED SALTIRE	<span class="font_support">(DejaVu: Not Yet)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26DE;</span><br />
	<span class="red">&#x26;#x26DE;</span>	FALLING DIAGONAL IN WHITE CIRCLE IN BLACK SQUARE	<span class="font_support">(DejaVu: Not Yet)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26DF;</span><br />
	<span class="red">&#x26;#x26DF;</span>	BLACK TRUCK	<span class="font_support">(DejaVu: Not Yet)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26E0;</span><br />
	<span class="red">&#x26;#x26E0;</span>	RESTRICTED LEFT ENTRY-1	<span class="font_support">(DejaVu: Not Yet)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26E1;</span><br />
	<span class="red">&#x26;#x26E1;</span>	RESTRICTED LEFT ENTRY-2	<span class="font_support">(DejaVu: Not Yet)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26E2;</span><br />
	<span class="red">&#x26;#x26E2;</span>	ASTRONOMICAL SYMBOL FOR URANUS	<span class="font_support">(DejaVu: Not Yet)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26E3;</span><br />
	<span class="red">&#x26;#x26E3;</span>	HEAVY CIRCLE WITH STROKE AND TWO DOTS ABOVE	<span class="font_support">(DejaVu: Not Yet)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26E4;</span><br />
	<span class="red">&#x26;#x26E4;</span>	PENTAGRAM	<span class="font_support">(DejaVu: Not Yet)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26E5;</span><br />
	<span class="red">&#x26;#x26E5;</span>	RIGHT-HANDED INTERLACED PENTAGRAM	<span class="font_support">(DejaVu: Not Yet)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26E6;</span><br />
	<span class="red">&#x26;#x26E6;</span>	LEFT-HANDED INTERLACED PENTAGRAM	<span class="font_support">(DejaVu: Not Yet)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26E7;</span><br />
	<span class="red">&#x26;#x26E7;</span>	INVERTED PENTAGRAM	<span class="font_support">(DejaVu: Not Yet)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26E8;</span><br />
	<span class="red">&#x26;#x26E8;</span>	BLACK CROSS ON SHIELD	<span class="font_support">(DejaVu: Not Yet)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26E9;</span><br />
	<span class="red">&#x26;#x26E9;</span>	SHINTO SHRINE	<span class="font_support">(DejaVu: Not Yet)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26EA;</span><br />
	<span class="red">&#x26;#x26EA;</span>	CHURCH	<span class="font_support">(DejaVu: Not Yet)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26EB;</span><br />
	<span class="red">&#x26;#x26EB;</span>	CASTLE	<span class="font_support">(DejaVu: Not Yet)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26EC;</span><br />
	<span class="red">&#x26;#x26EC;</span>	HISTORIC SITE	<span class="font_support">(DejaVu: Not Yet)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26ED;</span><br />
	<span class="red">&#x26;#x26ED;</span>	GEAR WITHOUT HUB	<span class="font_support">(DejaVu: Not Yet)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26EE;</span><br />
	<span class="red">&#x26;#x26EE;</span>	GEAR WITH HANDLES	<span class="font_support">(DejaVu: Not Yet)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26EF;</span><br />
	<span class="red">&#x26;#x26EF;</span>	MAP SYMBOL FOR LIGHTHOUSE	<span class="font_support">(DejaVu: Not Yet)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26F0;</span><br />
	<span class="red">&#x26;#x26F0;</span>	MOUNTAIN	<span class="font_support">(DejaVu: Not Yet)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26F1;</span><br />
	<span class="red">&#x26;#x26F1;</span>	UMBRELLA ON GROUND	<span class="font_support">(DejaVu: Not Yet)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26F2;</span><br />
	<span class="red">&#x26;#x26F2;</span>	FOUNTAIN	<span class="font_support">(DejaVu: Not Yet)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26F3;</span><br />
	<span class="red">&#x26;#x26F3;</span>	FLAG IN HOLE	<span class="font_support">(DejaVu: Not Yet)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26F4;</span><br />
	<span class="red">&#x26;#x26F4;</span>	FERRY	<span class="font_support">(DejaVu: Not Yet)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26F5;</span><br />
	<span class="red">&#x26;#x26F5;</span>	SAILBOAT	<span class="font_support">(DejaVu: Not Yet)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26F6;</span><br />
	<span class="red">&#x26;#x26F6;</span>	SQUARE FOUR CORNERS	<span class="font_support">(DejaVu: Not Yet)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26F7;</span><br />
	<span class="red">&#x26;#x26F7;</span>	SKIER	<span class="font_support">(DejaVu: Not Yet)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26F8;</span><br />
	<span class="red">&#x26;#x26F8;</span>	ICE SKATE	<span class="font_support">(DejaVu: Not Yet)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26F9;</span><br />
	<span class="red">&#x26;#x26F9;</span>	PERSON WITH BALL	<span class="font_support">(DejaVu: Not Yet)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26FA;</span><br />
	<span class="red">&#x26;#x26FA;</span>	TENT	<span class="font_support">(DejaVu: Not Yet)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26FB;</span><br />
	<span class="red">&#x26;#x26FB;</span>	JAPANESE BANK SYMBOL	<span class="font_support">(DejaVu: Not Yet)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26FC;</span><br />
	<span class="red">&#x26;#x26FC;</span>	HEADSTONE GRAVEYARD SYMBOL	<span class="font_support">(DejaVu: Not Yet)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26FD;</span><br />
	<span class="red">&#x26;#x26FD;</span>	FUEL PUMP	<span class="font_support">(DejaVu: Not Yet)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26FE;</span><br />
	<span class="red">&#x26;#x26FE;</span>	CUP ON BLACK SQUARE	<span class="font_support">(DejaVu: Not Yet)</span></li>
<li>&#x00A0;<span class="blueshadow">&#x26FF;</span><br />
	<span class="red">&#x26;#x26FF;</span>	WHITE FLAG WITH HORIZONTAL MIDDLE BLACK STRIPE	<span class="font_support">(DejaVu: Not Yet)</span></li>
</ol>
<div class="container footer"><p>Enter a Unicode Character to view more details at the <a href="https://util.unicode.org/UnicodeJsps/character.jsp?a=261D">Unicode</a> official site!</p>
<p>What is a Numerical Character Reference (<a href="https://en.wikipedia.org/wiki/Numeric_character_reference">NCR</a>)?</p>
</div>
</div>
</body>
</html>