<?php 
date_default_timezone_set('EST');
$page_heading = 'DistroTube VIM Tutorial';
$title = 'VIM Tutorial by DistroTube';
$lastMod = "Modified: " . date("D M j Y G:i:s T", getlastmod());
?>
<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8"> 
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>
    <?php print $title; ?>
  </title>
  <link rel="icon" type="image/ico" href="favicon.ico">
  <link rel="shortcut icon" type="image/ico" href="favicon.ico">
  <style>
/** if needed add style here */
  </style>
    <link 
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" 
        rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" 
        crossorigin="anonymous">    <!-- BOOTSTRAP STYLE -->
    <link 
        rel="stylesheet" 
        href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link 
        href="https://api.mapbox.com/mapbox-gl-js/v2.1.1/mapbox-gl.css" 
        rel="stylesheet">
    <link 
        href="css/notes.css" 
        rel="stylesheet" 
        type="text/css">
</head>

<body>

  <div id="pagewidth" class="container">
 
    <section id="header">  <!-- #HEADER -->
        <h1 class="bg-dark text-light text-end pe-3"><?php print $page_heading; ?></h1>
    </section>
    <section class="content">
      <div class="notes">                           
        <h2>The VIM Tutorial by DistroTube</h2>
            <dl>
                <dt>Normal-mode to Insert-mode / Visual-mode</dt>
                <dd>
                    <ul>
                        <li><strong>Insert</strong>-mode: just hit <kbd>i</kbd>. Exit insert-mode with <kbd>esc</kbd>. Note that other keys can be configured.</li>
                        <li><strong>Visual</strong>-mode: <kbd>v</kbd> - Visual mode allows for multi-line selection</li>
                    </ul></dd>
                <dt>Common Shortcuts for Cursor Movement</dt>
                <dd>
                    Note that these movement commands happen in <strong>Normal mode</strong>
                    <dt>Basic directions</dt>
                    <dd>
                        <ul>
                            <li>Left: <kbd>h</kbd></li>
                            <li>Down: <kbd>j</kbd></li>
                            <li>Up: <kbd>k</kbd></li>
                            <li>Right: <kbd>l</kbd></li>

                        </ul>                        
                    </dd>
                    <dt>Jump to &#x201c;X&#x201d;</dt>
                    <dd>
                        
                        <ul>
                            <li><kbd>gg</kbd> - move to very first char of <strong>document</strong></li>
                            <li><kbd>[shift] + G</kbd> - move to last char of <strong>document</strong></li>
                            <li>within-Line movement: <kbd>0</kbd> (zero) - move the cursor to the first char of the line.</li>
                            <li>
                        </ul>
                    </dd>

                </dd>

            </dl>

      </div>                                        <!--    .notes      -->
    </section>
    <section class="footer px-4">                   <!--    .FOOTER     -->
        <div class="row gx-5">
            <div class="col"><div class="p-3 border bg-light"> Based on Notes by <a href="https://github.com/ajaxStardust" target="_blank" title="View original">@ajaxStardust</a> <em>Laravel</em> notes:</div></div>
            <div class="col"><div class="p-3 border bg-light text-end"><kbd><?php echo $lastMod; ?></kbd></div></div>
        </div>
    </section>      
  </div>                                            <!--    .content  -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
</body>
</html>