<?php
/*
 * adb_simplest/template.phtml
 *
 * Copyright 2023 @ajaxStardust <flux@mx23>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301, USA.
 *
 *
 */

header('Access-Control-Allow-Origin: *'); // ENABLE CORS (Cross-Origin Request) policy allow all - CAUTION: not-ready-for-prime-time player
date_default_timezone_set('EST');
$page_heading = '&#x201c;Simple Template&#x201d; ';
$title = 'Basic TEMPLATE';
$lastMod = "Modified: " . date("D M j Y G:i:s T", getlastmod());
?>
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>
    <?php print $title; ?>
  </title>
  <link rel="icon" type="image/ico" href="favicon.ico">
  <link rel="shortcut icon" type="image/ico" href="favicon.ico">

  <style>
    .tsw {
      font-family: "source serif pro";
      font-size: 1.2rem;
      font-style: italic;
    }

    /** if needed add style here
                                ** NOTE THE NEW favICON code here:
                                **
                                */
  </style>
  <link rel="icon" href="./favicon.ico" sizes="32x32">
  <link rel="icon" href="./favicon.ico" sizes="192x192">
  <link rel="apple-touch-icon" href="./favicon.ico">
  <meta name="msapplication-TileImage" content="<!-- http://.file./ -->">


  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
  <!-- BOOTSTRAP STYLE -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
  <link href="https://api.mapbox.com/mapbox-gl-js/v2.1.1/mapbox-gl.css" rel="stylesheet">
  <link href="assets/css/notes.css" rel="stylesheet" type="text/css">
</head>

<body>

  <div id="pagewidth" class="container"> <!--    :begin    class:content        -->

    <section id="header"> <!-- #HEADER -->
      <h1 class="bg-dark text-light text-end pe-3">
        <?php print $page_heading; ?>
      </h1>
    </section>
    <section id="general_notes">
      <h2>Purpose of this File</h2>
        <h3>Why the WordPress Headings Etc?</h3>
        <p>And why if you look at the code will you see those wordpress serialized theme.json markup shits?</p>
        <p>Why?</p>
<p>Why?</p>
        <h3>Here's why:</h3>
        <p>The idea was to have a place to see what the WordPress block editor code looks like, in the event that a post requires manual editing of that detail.</p>
      <div class="notes">
<!-- wp:group {"style":{"color":{"background":"#eeeeee"}},"layout":{"type":"constrained","contentSize":"%"}} -->
<div class="wp-block-group has-background" style="background-color:#eeeeee"><!-- wp:group {"layout":{"type":"flex","flexWrap":"wrap","justifyContent":"space-between"}} -->
<div class="wp-block-group"><!-- wp:group {"layout":{"type":"constrained"},"fontSize":"normal"} -->
<div class="wp-block-group has-normal-font-size"><!-- wp:navigation {"ref":5743,"icon":"menu","className":"site-navigation","style":{"spacing":{"blockGap":"var:preset|spacing|40"},"typography":{"fontSize":"17px","fontStyle":"normal","fontWeight":"600"}}} /--></div>
<!-- /wp:group -->

<!-- wp:group {"layout":{"type":"flex","flexWrap":"nowrap"}} -->
<div class="wp-block-group"><!-- wp:social-links {"size":"has-normal-icon-size","className":"is-style-default"} -->
<ul class="wp-block-social-links has-normal-icon-size is-style-default"><!-- wp:social-link {"url":"#","service":"facebook"} /-->

<!-- wp:social-link {"url":"#","service":"instagram"} /-->

<!-- wp:social-link {"url":"#","service":"twitter"} /-->

<!-- wp:social-link {"url":"#","service":"youtube"} /-->

<!-- wp:social-link {"url":"#","service":"linkedin"} /--></ul>
<!-- /wp:social-links --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"style":{"border":{"bottom":{"color":"#eeeeee","width":"1px"}}},"backgroundColor":"background","layout":{"type":"constrained","contentSize":"%"}} -->
<div class="wp-block-group has-background-background-color has-background" style="border-bottom-color:#eeeeee;border-bottom-width:1px"><!-- wp:group {"layout":{"type":"flex","flexWrap":"nowrap","justifyContent":"center"}} -->
<div class="wp-block-group"><!-- wp:site-title {"style":{"typography":{"textTransform":"uppercase","fontStyle":"normal","fontWeight":"700","fontSize":"4rem"}},"fontFamily":"oswald"} /--></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"style":{"border":{"bottom":{"color":"var:preset|color|primary","width":"3px"}}},"backgroundColor":"background","layout":{"type":"constrained"}} -->
<div class="wp-block-group has-background-background-color has-background" style="border-bottom-color:var(--wp--preset--color--primary);border-bottom-width:3px"><!-- wp:group {"layout":{"type":"flex","flexWrap":"nowrap","justifyContent":"center"},"fontSize":"normal"} -->
<div class="wp-block-group has-normal-font-size"><!-- wp:navigation {"ref":5744} /--></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"style":{"spacing":{"padding":{"top":"var:preset|spacing|60","right":"var:preset|spacing|50","bottom":"var:preset|spacing|60","left":"var:preset|spacing|50"},"blockGap":"0"}},"layout":{"type":"default"}} -->
<div class="wp-block-group" style="padding-top:var(--wp--preset--spacing--60);padding-right:var(--wp--preset--spacing--50);padding-bottom:var(--wp--preset--spacing--60);padding-left:var(--wp--preset--spacing--50)"><!-- wp:columns -->
<div class="wp-block-columns"><!-- wp:column {"width":"66.66%"} -->
<div class="wp-block-column" style="flex-basis:66.66%"><!-- wp:post-title {"level":1,"fontSize":"regular"} /-->

<!-- wp:post-content /--></div>
<!-- /wp:column -->

<!-- wp:column {"width":"33.33%"} -->
<div class="wp-block-column" style="flex-basis:33.33%"><!-- wp:query {"queryId":14,"query":{"perPage":10,"pages":0,"offset":0,"postType":"web-dev-resource","order":"desc","orderBy":"date","author":"","search":"","exclude":[],"sticky":"","inherit":false,"parents":[]}} -->
<div class="wp-block-query"><!-- wp:post-template -->
<!-- wp:columns {"verticalAlignment":"center"} -->
<div class="wp-block-columns are-vertically-aligned-center"><!-- wp:column {"verticalAlignment":"center","width":"25%"} -->
<div class="wp-block-column is-vertically-aligned-center" style="flex-basis:25%"><!-- wp:post-featured-image {"isLink":true,"width":"80px","height":"80px"} /--></div>
<!-- /wp:column -->

<!-- wp:column {"verticalAlignment":"center","width":"75%"} -->
<div class="wp-block-column is-vertically-aligned-center" style="flex-basis:75%"><!-- wp:post-title {"isLink":true} /--></div>
<!-- /wp:column --></div>
<!-- /wp:columns -->
<!-- /wp:post-template --></div>
<!-- /wp:query --></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div>
<!-- /wp:group -->

<!-- wp:group {"style":{"color":{"background":"#37373f"},"spacing":{"padding":{"top":"60px","bottom":"60px"}}},"layout":{"type":"flex","flexWrap":"nowrap","justifyContent":"center"}} -->
<div class="wp-block-group has-background" style="background-color:#37373f;padding-top:60px;padding-bottom:60px"><!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:columns -->
<div class="wp-block-columns"><!-- wp:column -->
<div class="wp-block-column"><!-- wp:heading {"textColor":"background","fontSize":"medium"} -->
<h2 class="wp-block-heading has-background-color has-text-color has-medium-font-size">About Us</h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"textColor":"background"} -->
<p class="has-background-color has-text-color">It has survived not only five centuries, but also the
                    leap into electronic typesetting, remaining essentially unchanged. It has survived not only five
                    centurie.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"textColor":"background"} -->
<p class="has-background-color has-text-color">Download this theme now and make awesome site today.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:heading {"textColor":"background","fontSize":"medium"} -->
<h2 class="wp-block-heading has-background-color has-text-color has-medium-font-size">Recent Posts</h2>
<!-- /wp:heading -->

<!-- wp:latest-posts /--></div>
<!-- /wp:column -->

<!-- wp:column -->
<div class="wp-block-column"><!-- wp:heading {"textColor":"background","fontSize":"medium"} -->
<h2 class="wp-block-heading has-background-color has-text-color has-medium-font-size">Categories</h2>
<!-- /wp:heading -->

<!-- wp:categories /--></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:group {"style":{"color":{"background":"#2e2e35"},"spacing":{"padding":{"top":"40px","bottom":"40px"}}},"layout":{"type":"flex","flexWrap":"nowrap","justifyContent":"center","orientation":"vertical"}} -->
<div class="wp-block-group has-background" style="background-color:#2e2e35;padding-top:40px;padding-bottom:40px"><!-- wp:social-links {"layout":{"type":"flex","justifyContent":"center"}} -->
<ul class="wp-block-social-links"><!-- wp:social-link {"url":"#","service":"facebook"} /-->

<!-- wp:social-link {"url":"#","service":"twitter"} /-->

<!-- wp:social-link {"url":"#","service":"instagram"} /-->

<!-- wp:social-link {"url":"#","service":"youtube"} /-->

<!-- wp:social-link {"url":"#","service":"linkedin"} /--></ul>
<!-- /wp:social-links -->

<!-- wp:paragraph {"align":"center","textColor":"background"} -->
<p class="has-text-align-center has-background-color has-text-color">All Rights Reserved 2022.</p>
<!-- /wp:paragraph -->

<!-- wp:group {"align":"wide","layout":{"type":"flex","justifyContent":"center","orientation":"horizontal"}} -->
<div class="wp-block-group alignwide"><!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"align":"right","style":{"spacing":{"padding":{"top":"0px","right":"0px","bottom":"0px","left":"0px"}}},"textColor":"background"} -->
<p class="has-text-align-right has-background-color has-text-color" style="padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px">Proudly powered by <a href="https://wordpress.org" target="_blank" rel="noreferrer noopener">WordPress</a></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"align":"right","textColor":"background"} -->
<p class="has-text-align-right has-background-color has-text-color">Theme: Fairy Grid FSE by <a href="https://www.candidthemes.com/" target="_blank" rel="noreferrer noopener">Candid Themes.</a>
            </p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->
        <dl>
          <dt class="keyTerms pointer">Example Collapse <span class="normal blue pointer" id="show_n01"
              onclick="swap_text('show_n01','notes_01') ">[toggle...]</span>
          </dt>
          <dd id="notes_01" class="displaynone"> <!-- hidden then revealed -->
            <p>Something you want to be collapsed at first:
              <code>some code maybe</code> or</p>
            <pre>maybe some
&#x3c;preformatted&#x3e;
text here.</pre>
          </dd>

          <dt class="keyTerms pointer">Reveal random: <span class="normal blue pointer" id="show_n02"
              onclick="swap_text('show_n02','notes_02') ">[toggle...]</span>
          </dt>
          <dd id="notes_02" class="displaynone"> <!-- hidden then revealed -->
            <p>Some Random content
          </dd>
        </dl>

        <!-- END NOTES --><!-- END NOTES -->
        <!-- END NOTES --><!-- END NOTES -->


      </div> <!-- $ end .notes div -->
    </section>
    <section> <!-- :begin #_GLOSSARY  -->
      <div>
        <h2>Glossary:</h2>
        <h3>Key Terms about <?php print $page_heading; ?></h3>
        <dl>
        <dt class="pointer">Show Glossary<span class="normal blue pointer" id="show_g01"
              onclick="swap_text('show_g01','glossary_01') ">[toggle...]</span>
          </dt>
          <dd id="glossary_01" class="displaynone">
            <p>Maybe this is a note about a framework&apos;s folder structure...</p>
            <pre>#       /var/www/html/framework_name/
#       |-- some.file.name
#       |-- some.ts
#       |-- some.json
#       |-- some.js</pre>
<p>Remember: There are tools, such as the Linux command line tool, <code>tree</code> which can generate the
                tree in various formats including <strong>JSON and HTML</strong>. E.g. <code>tree -J</code> or <code>tree -H http://path/of/dir</code></p>
            <p><kbd>apt install tree</kbd></p>
          </dd>
        </dl>
      </div> <!-- $ :end #_glossary -->
    </section>
    <footer class="footer px-4"> <!--    .FOOTER     -->
      <div class="row gx-5">
        <div class="col">
          <div class="p-3 border bg-light"> Based on Notes by <a href="https://github.com/ajaxStardust" target="_blank"
              title="View original">@ajaxStardust</a> <em>Laravel</em> notes:</div>
        </div>
        <div class="col">
          <div class="p-3 border bg-light text-end"><kbd>
              <?php echo $lastMod; ?>
            </kbd></div>
        </div>
      </div>
    </footer>
  </div><!--    $ :end    END class.content (former id.maincol)    $    -->

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
    crossorigin="anonymous"></script>
  <script src="assets/js/showme-hideme.js"></script>

</body>

</html>
