<?php 
date_default_timezone_set('EST');
$page_heading = 'Various Disjointed Notes RE: WP Dev.';
$title = 'My WOrdPress Dev notes';
$lastMod = "Modified: " . date("D M j Y G:i:s T", getlastmod());
?>
<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8"> 
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>
    <?php print $title; ?>
  </title>
  <link rel="icon" type="image/ico" href="favicon.ico">
  <link rel="shortcut icon" type="image/ico" href="favicon.ico">
  <style>
/** if needed add style here */
  </style>
    <link 
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" 
        rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" 
        crossorigin="anonymous">    <!-- BOOTSTRAP STYLE -->
    <link 
        rel="stylesheet" 
        href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link 
        href="https://api.mapbox.com/mapbox-gl-js/v2.1.1/mapbox-gl.css" 
        rel="stylesheet">
    <link 
        href="assets/css/notes.css" 
        rel="stylesheet" 
        type="text/css">
</head>

<body>

  <div id="pagewidth" class="container">
 
    <section id="header">  <!-- #HEADER -->
        <h1 class="bg-dark text-light text-end pe-3"><?php print $page_heading; ?></h1>
    </section>
    <section class="content">
      <div class="notes">      
      <h2>General WordPress Development Notes</h2>
      <h3>The plugin generated xxx characters of unexpected output during activation</h3>                     <!-- ^ .notes ^ -->  
      <p>You should never <code>echo</code> anything directly and your <code>&lt;php?</code> tag should start right at the beginning and <code>?&gt;</code> end right at the end. My 2 character unexpected input was just because of a new line before <code>&lt;php?</code>
      </p>
</div>
<div class="notes">
        <h2>Manual Debugging</h2>
        <p>The following is a bit of code to put into a function for manual debugging. Nothing special here.</p>
        <pre>        // test_echo ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        $test_echo = &apos;&lt;div class=&quot;indent_for_dash&quot;&gt;&apos;;
        $test_echo .=  &apos;&lt;div class=&quot;blue&quot;&gt;File: &apos;. __FILE__ . &apos;:&apos; .__LINE__.&apos;&lt;br&gt;&apos;;
        $test_echo .=  &apos;&lt;div class=&quot;grey&quot;&gt;At function: &lt;span class=&quot;bold red&quot;&gt;&apos; . __FUNCTION__ .&apos;&lt;/span&gt;:&apos; .__LINE__ .&apos;&lt;/div&gt;&apos;;
        $test_echo .=  &apos;&lt;div class=&quot;grey&quot;&gt;this-&gt;basenme - &lt;strong class=&quot;darkgrey&quot;&gt;&apos; . pathinfo(__FILE__, PATHINFO_BASENAME) .&apos;&lt;/strong&gt;:&apos;.__LINE__.&apos;&lt;/div&gt;&lt;/div&gt;&apos;;
        echo $test_echo;</pre>
  <h2>Notes about experiencing errors.</h2>
  <h3>Specifically, advice on <a href="https://wordpress.org/support/topic/call_user_func_array-expects-parameter-1-to-be-a-valid-callback-21/#post-14931481">how to debug manually</a>:</h3>
  <p>The error which led me there was <code>Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'twl_display_tab_general' not found or invalid function name in /var/www/html/wp_clean/wp-includes/<span class="code bold">class-wp-hook.php</span> on line <strong>308</strong></code></p>
  <aside class="serif">theme file presumed at time of writing, however this is probably specific to that user's own question. i probably want to add this to my erring file. That is, the file containing <code class="bold">twl_display_tab_general()</code></aside>
  <p>Add the following to functions.php and add the following code:<pre>
function regis_options($args) {
   return $args;
}</pre>
</p>
<p>Add the following to  class-wp-hook.php:
  <pre>public function regis_options($args) {
echo &apos;&lt;pre&gt;&apos; . var_export($args, true) . &apos;&lt;/pre&gt;&apos;;
echo &apos;&lt;pre&gt;&apos; . var_dump(debug_backtrace()) . &apos;&lt;/pre&gt;&apos;;
return $args;
}</pre>
      </div>                                        <!-- $ .notes     -->
    </section>
    <section class="footer px-4">                   <!-- .FOOTER        -->
        <div class="row gx-5">
            <div class="col">
                <div class="p-3 border bg-light"> Based on Notes by <a href="https://github.com/ajaxStardust" target="_blank" title="View original">@ajaxStardust</a> <em>Laravel</em> notes:</div>
            </div>
            <div class="col">
                <div class="p-3 border bg-light text-end"><kbd><?php echo $lastMod; ?></kbd></div>
            </div>
        </div>
    </section>      
  </div>                                            <!--    .content  -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
</body>
</html>