<?php
/*
 * adb_simplest/template.phtml
 *
 * Copyright 2023 @ajaxStardust <flux@mx23>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301, USA.
 *
 *
 */

header('Access-Control-Allow-Origin: *'); // ENABLE CORS (Cross-Origin Request) policy allow all - CAUTION: not-ready-for-prime-time player
date_default_timezone_set('EST');

if (!defined('ABSOLUTELOCATION')) {
    define('ABSOLUTELOCATION', rtrim(dirname(__FILE__), 'public/inc'));
}
$abspath = ABSOLUTELOCATION;

$http_type = $_SERVER['SERVER_SOFTWARE'];
$http_name = $_SERVER['SERVER_NAME'];
$http_ip = $_SERVER['SERVER_ADDR'];
$httpname = $http_name;
if (preg_match('@(10\.0\.0\.\d+|192\.\d+\.\d+\.\d+)@', $http_ip)) {
    $abspath = '<code class="info">' . $abspath . '</code>';
} else {
    $abspath = 'is simply a PHP value which relies on server variables<code>define( ABSOLUTELOCATION , rtrim(dirname(__FILE__), inc))</code>';
}

$parent_dir = str_ireplace('/var/www/html','',__DIR__);

$page_heading = '&#x201c;Simple Template&#x201d; ';
$title = $http_ip.' - '.$parent_dir.' - EditPlus_IV TEMPLATE';
$lastMod = "Modified: " . date("D M j Y G:i:s T", getlastmod());

?>
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>
    <?php print $title; ?>
  </title>
  <link rel="icon" type="image/ico" href="favicon.ico" sizes="16x16">
  <link rel="shortcut icon" type="image/ico" href="favicon.ico">
  <link rel="icon" href="./favicon.ico" sizes="32x32">
  <link rel="icon" href="./favicon.ico" sizes="192x192">
  <link rel="apple-touch-icon" href="./favicon.ico">
  <meta name="msapplication-TileImage" content="http://.file./ -->">


  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
  <!-- BOOTSTRAP STYLE -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
  <link href="https://api.mapbox.com/mapbox-gl-js/v2.1.1/mapbox-gl.css" rel="stylesheet">
  <link href="assets/css/notes.css" rel="stylesheet" type="text/css">
    <style>
    <![CDATA[
    .tsw {
      font-family: "source serif pro";
      font-size: 1.2rem;
      font-style: italic;
    }

    /** if needed add style here
                                ** NOTE THE NEW favICON code here:
                                **
                                */
  </style>
</head>

<body>

  <div id="pagewidth" class="container"> <!--    :begin    class:content        -->

    <section id="header"> <!-- #HEADER -->
      <h1 class="bg-dark text-light text-end pe-3">
        <?php print $page_heading; ?>
      </h1>
    </section>
    <section id="general_notes">
      <h2>General Notes</h2>
      <div class="notes">
        <!-- ADD NOTES HERE --><!-- ADD NOTES HERE -->
        <!-- ADD NOTES HERE --><!-- ADD NOTES HERE -->
        <!-- ADD NOTES HERE --><!-- ADD NOTES HERE -->
        <dl>
          <dt class="keyTerms pointer">Example Collapse <span class="normal blue pointer" id="show_n01"
              onclick="swap_text('show_n01','notes_01') ">[toggle...]</span>
          </dt>
          <dd id="notes_01" class="displaynone"> <!-- hidden then revealed -->
            <p>Something you want to be collapsed at first:
              <code>some code maybe</code> or</p>
            <pre>maybe some
&#x3c;preformatted&#x3e;
text here.</pre>
          </dd>

          <dt class="keyTerms pointer">Peek-a-boo Code:<span class="normal blue pointer" id="show_n02"
              onclick="swap_text('show_n02','notes_02') ">[toggle...]</span>
          </dt>
          <dd id="notes_02" class="displaynone"> <!-- hidden then revealed -->
            <pre>
function register_custom_post_type() {
    register_post_type('form_log', array(
        'labels' => array(
            'name' => __('Form Logs'),
            'singular_name' => __('Form Log')
        ),
        'public' => true,
        'has_archive' => true,
        'supports' => array('title', 'editor'),
    ));
}
add_action('init', 'register_custom_post_type');</pre>
          </dd>
        </dl>
<!-- wp:paragraph -->
<p>I just wanted to post a quick note to say that I REALLY like the new Vivaldi Sessions panel. Once you have some tabs open for whatever you're doing, you can just right click in the panel area, and "save as session". Not sure I'll be doing much saving, as that sort of thing just makes my ADHD go crazy. But that's just me. I'm sure it's a wonderful feature, for <em>normal</em> people. </p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>At first, I was like "<em>what the heck is going on here!?</em>"<br><br>Then, <strong>being one who uses the vertical tabs</strong> in <strong>Microsoft Edge</strong> (on those less than common instances when I use that browser), I suddenly <strong>realized what was going on</strong>. But this takes it the step further that it needed! It's so cool that-- in Vivaldi's variation-- you can </p>
<!-- /wp:paragraph -->

<!-- wp:list -->
<ul><!-- wp:list-item -->
<li>Shrink the tab panel (Sessions) down to just the Favicons for larger screen viewing area</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li>Expand the tab panel, making it wider to see the Page Title, etc.</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li>Whatever you want! It's just that cool!</li>
<!-- /wp:list-item --></ul>
<!-- /wp:list -->

<!-- wp:paragraph -->
<p>The Vivaldi team may have a few things to work out yet, perhaps, they are the ones ON THE RIGHT TRACK with making the web browser better! I haven't put it down since I discovered it! Not unlike when I was a teenager, and first discovered Playb... the play book. yeah. the play book. </p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>My favorite thing about the new Vivaldi tab panel is that the SCREEN REAL ESTATE is greatly EXPANDED! There's nothing at the top of the screen, just as it should be. Widen that playing field! (see above, RE: play book) hee hee.<br><br>In my opinion, the other browser developers have nothing on Vivaldi. They just don't get it in the same way. That's for certain! And to heck with Spark email. Yeah, you know what i'm talking about. This works better for my productivity stream. Maybe it's because I'm an old-school Opera user. And I suppose a lot of Vivaldi users would probably share in my sentiment about how it picked-up where Opera abandoned us back around the death of Presto. </p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>I'd have spoken sooner on this, but I was a bit&nbsp;<a href="https://social.vivaldi.net/@ajaxStardust/111631986738998972">out of the loop for a while</a>, and since my g/f has been taking care of me as I convalesce, my discovery of this coolness was a bit delayed.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p>In any case! Keep it going, Vivaldi people! I both <em>rocks</em>, and <em>rolls</em>-- that is to say-- it's got both kinds of music! Rock and roll!</p>
<!-- /wp:paragraph -->

<!-- wp:coblocks/gif {"width":920,"height":695} -->
<figure class="wp-block-coblocks-gif is-resized"><img src="https://file.coffee/u/g2Cy-VIeA3QShPyGaHP6H.gif" alt="Vivaldi Sessions Panel" width="920" height="695"/></figure>
<!-- /wp:coblocks/gif -->
      </div> <!-- $ end .notes div -->
    </section>
    <section> <!-- :begin #_GLOSSARY  -->
      <div>
        <h2>Glossary:</h2>
        <h3>Key Terms about <?php print $page_heading; ?></h3>
        <dl>
        <dt class="pointer">Show Glossary<span class="normal blue pointer" id="show_g01"
              onclick="swap_text('show_g01','glossary_01') ">[toggle...]</span>
          </dt>
          <dd id="glossary_01" class="displaynone">
            <p>Maybe this is a note about a framework&apos;s folder structure...</p>
            <pre>#       /var/www/html/framework_name/
#       |-- some.file.name
#       |-- some.ts
#       |-- some.json
#       |-- some.js</pre>
<p>Remember: There are tools, such as the Linux command line tool, <code>tree</code> which can generate the
                tree in various formats including <strong>JSON and HTML</strong>. E.g. <code>tree -J</code> or <code>tree -H http://path/of/dir</code></p>
            <p><kbd>apt install tree</kbd></p>
          </dd>
        </dl>
      </div> <!-- $ :end #_glossary -->
    </section>
    <footer class="footer px-4"> <!--    .FOOTER     -->
      <div class="row gx-5">
        <div class="col">
          <div class="p-3 border bg-light"> Based on Notes by <a href="https://github.com/ajaxStardust" target="_blank"
              title="View original">@ajaxStardust</a> <em>Laravel</em> notes:</div>
        </div>
        <div class="col">
          <div class="p-3 border bg-light text-end"><kbd>
              <?php echo $lastMod; ?>
            </kbd></div>
        </div>
      </div>
    </footer>
  </div><!--    $ :end    END class.content (former id.maincol)    $    -->

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
    crossorigin="anonymous"></script>
  <script src="assets/js/showme-hideme.js"></script>

</body>

</html>
